// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminUserPermissions</c>
/// </summary>
public class AdminUserPermissions {
	public bool PreventEditServerSettings { get; set; }
	public bool PreventServerShutdown { get; set; }
	public bool PreventChangePassword { get; set; }
	public bool AllowEditBranding { get; set; }
	public bool AllowEditEmailOptions { get; set; }
	public bool AllowEditRemoteStorage { get; set; }
	public bool AllowEditWebhooks { get; set; }
	public bool DenyConstellationRole { get; set; }

	public AdminUserPermissions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminUserPermissions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminUserPermissions>(jsStr);
	}

}
}
