// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminU2FRegistration</c>
/// </summary>
[Obsolete("Deprecated since Comet version 21.12.0")]
public class AdminU2FRegistration {

	[JsonPropertyName("Description")]
	public string Description { get; set; } = string.Empty;

	[JsonPropertyName("RegisterTime")]
	//Unix timestamp, in seconds.
	public long RegisterTime { get; set; }

	[JsonPropertyName("Registration")]
	public byte[] Registration { get; set; }

	public AdminU2FRegistration(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminU2FRegistration FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminU2FRegistration>(jsStr);
	}

}
}
