// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminOptions</c>
/// </summary>
public class AdminOptions {

	[JsonPropertyName("Policy")]
	public PolicyOptions Policy { get; set; }

	public AdminOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminOptions>(jsStr);
	}

}
}
