// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminSecurityOptions</c>
/// </summary>
public class AdminSecurityOptions {
	public long PasswordFormat { get; set; }
	public string Password { get; set; } = string.Empty;
	public bool AllowPasswordLogin { get; set; }
	public bool AllowPasswordAndTOTPLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]
	public bool AllowPasswordAndU2FLogin { get; set; }
	public bool AllowPasswordAndWebAuthnLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]
	public List<AdminU2FRegistration> U2FRegistrations { get; set; }
	public List<AdminWebAuthnRegistration> WebAuthnRegistrations { get; set; }
	public long TOTPKeyEncryptionFormat { get; set; }
	public string TOTPKey { get; set; } = string.Empty;
	public string IPWhitelist { get; set; } = string.Empty;

	public AdminSecurityOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminSecurityOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminSecurityOptions>(jsStr);
	}

}
}
