// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminAccountPropertiesResponse</c>
/// </summary>
public class AdminAccountPropertiesResponse {
	public string OrganizationID { get; set; } = "";
	public AdminUserPermissions Permissions { get; set; } = new AdminUserPermissions();
	public AdminSecurityOptions Security { get; set; } = new AdminSecurityOptions();

	public AdminAccountPropertiesResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminAccountPropertiesResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminAccountPropertiesResponse>(jsStr);
	}

}
}
