// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminEmailOptions</c>
/// </summary>
public class AdminEmailOptions {
	public string FromEmail { get; set; } = "";
	public string FromName { get; set; } = "";

	public AdminEmailOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminEmailOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminEmailOptions>(jsStr);
	}

}
}
