// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AdminEmailOptions</c>
/// </summary>
public class AdminEmailOptions {

	[JsonPropertyName("FromEmail")]
	public string FromEmail { get; set; } = string.Empty;

	[JsonPropertyName("FromName")]
	public string FromName { get; set; } = string.Empty;

	public AdminEmailOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AdminEmailOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AdminEmailOptions>(jsStr);
	}

}
}
