// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AllowedAdminUser</c>
/// </summary>
public class AllowedAdminUser {

	[JsonPropertyName("Username")]
	public string Username { get; set; } = string.Empty;

	[JsonPropertyName("OrganizationID")]
	public string OrganizationID { get; set; } = string.Empty;

	[JsonPropertyName("ExternalAuthenticationSource")]
	public string ExternalAuthenticationSource { get; set; } = string.Empty;

	[JsonPropertyName("PasswordFormat")]
	//One of the PASSWORD_FORMAT_ constants
	public long PasswordFormat { get; set; }

	[JsonPropertyName("Password")]
	public string Password { get; set; } = string.Empty;

	[JsonPropertyName("AllowPasswordLogin")]
	public bool AllowPasswordLogin { get; set; }

	[JsonPropertyName("AllowPasswordAndTOTPLogin")]
	public bool AllowPasswordAndTOTPLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]

	[JsonPropertyName("AllowPasswordAndU2FLogin")]
	public bool AllowPasswordAndU2FLogin { get; set; }

	[JsonPropertyName("AllowPasswordAndWebAuthnLogin")]
	public bool AllowPasswordAndWebAuthnLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]

	[JsonPropertyName("U2FRegistrations")]
	public List<AdminU2FRegistration> U2FRegistrations { get; set; }

	[JsonPropertyName("WebAuthnRegistrations")]
	public List<AdminWebAuthnRegistration> WebAuthnRegistrations { get; set; }

	[JsonPropertyName("RequirePasswordChange")]
	public bool RequirePasswordChange { get; set; }

	[JsonPropertyName("TOTPKeyEncryptionFormat")]
	//One of the ENCRYPTIONMETHOD_ constants
	public long TOTPKeyEncryptionFormat { get; set; }

	[JsonPropertyName("TOTPKey")]
	public string TOTPKey { get; set; } = string.Empty;

	[JsonPropertyName("IPWhitelist")]
	//A regular expression in Go regex syntax, for which IP addresses are allowed to authenticate as this admin account
	public string IPWhitelist { get; set; } = string.Empty;

	[JsonPropertyName("Permissions")]
	public AdminUserPermissions Permissions { get; set; }

	public AllowedAdminUser(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AllowedAdminUser FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AllowedAdminUser>(jsStr);
	}

	public AdminSecurityOptions GetEmbeddedAdminSecurityOptions() => new AdminSecurityOptions {
		PasswordFormat = this.PasswordFormat,
		Password = this.Password,
		AllowPasswordLogin = this.AllowPasswordLogin,
		AllowPasswordAndTOTPLogin = this.AllowPasswordAndTOTPLogin,
		AllowPasswordAndU2FLogin = this.AllowPasswordAndU2FLogin,
		AllowPasswordAndWebAuthnLogin = this.AllowPasswordAndWebAuthnLogin,
		U2FRegistrations = this.U2FRegistrations,
		WebAuthnRegistrations = this.WebAuthnRegistrations,
		RequirePasswordChange = this.RequirePasswordChange,
		TOTPKeyEncryptionFormat = this.TOTPKeyEncryptionFormat,
		TOTPKey = this.TOTPKey,
		IPWhitelist = this.IPWhitelist,
	};

	public void SetEmbeddedAdminSecurityOptions(AdminSecurityOptions other){
		this.PasswordFormat = other.PasswordFormat;
		this.Password = other.Password;
		this.AllowPasswordLogin = other.AllowPasswordLogin;
		this.AllowPasswordAndTOTPLogin = other.AllowPasswordAndTOTPLogin;
		this.AllowPasswordAndU2FLogin = other.AllowPasswordAndU2FLogin;
		this.AllowPasswordAndWebAuthnLogin = other.AllowPasswordAndWebAuthnLogin;
		this.U2FRegistrations = other.U2FRegistrations;
		this.WebAuthnRegistrations = other.WebAuthnRegistrations;
		this.RequirePasswordChange = other.RequirePasswordChange;
		this.TOTPKeyEncryptionFormat = other.TOTPKeyEncryptionFormat;
		this.TOTPKey = other.TOTPKey;
		this.IPWhitelist = other.IPWhitelist;
	}

}
}
