// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AllowedAdminUser</c>
/// </summary>
public class AllowedAdminUser {
	public string Username { get; set; } = "";
	public string OrganizationID { get; set; } = "";
	public string ExternalAuthenticationSource { get; set; } = "";
	public long PasswordFormat { get; set; }
	public string Password { get; set; } = "";
	public bool AllowPasswordLogin { get; set; }
	public bool AllowPasswordAndTOTPLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]
	public bool AllowPasswordAndU2FLogin { get; set; }
	public bool AllowPasswordAndWebAuthnLogin { get; set; }

	[Obsolete("Deprecated since Comet version 21.12.0")]
	public List<AdminU2FRegistration> U2FRegistrations { get; set; } = new List<AdminU2FRegistration>();
	public List<AdminWebAuthnRegistration> WebAuthnRegistrations { get; set; } = new List<AdminWebAuthnRegistration>();
	public long TOTPKeyEncryptionFormat { get; set; }
	public string TOTPKey { get; set; } = "";
	public string IPWhitelist { get; set; } = "";
	public AdminUserPermissions Permissions { get; set; } = new AdminUserPermissions();

	public AllowedAdminUser(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AllowedAdminUser FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AllowedAdminUser>(jsStr);
	}

	public AdminSecurityOptions GetEmbeddedAdminSecurityOptions() => new AdminSecurityOptions {
		PasswordFormat = this.PasswordFormat,
		Password = this.Password,
		AllowPasswordLogin = this.AllowPasswordLogin,
		AllowPasswordAndTOTPLogin = this.AllowPasswordAndTOTPLogin,
		AllowPasswordAndU2FLogin = this.AllowPasswordAndU2FLogin,
		AllowPasswordAndWebAuthnLogin = this.AllowPasswordAndWebAuthnLogin,
		U2FRegistrations = this.U2FRegistrations,
		WebAuthnRegistrations = this.WebAuthnRegistrations,
		TOTPKeyEncryptionFormat = this.TOTPKeyEncryptionFormat,
		TOTPKey = this.TOTPKey,
		IPWhitelist = this.IPWhitelist,
	};

	public void SetEmbeddedAdminSecurityOptions(AdminSecurityOptions other){
		this.PasswordFormat = other.PasswordFormat;
		this.Password = other.Password;
		this.AllowPasswordLogin = other.AllowPasswordLogin;
		this.AllowPasswordAndTOTPLogin = other.AllowPasswordAndTOTPLogin;
		this.AllowPasswordAndU2FLogin = other.AllowPasswordAndU2FLogin;
		this.AllowPasswordAndWebAuthnLogin = other.AllowPasswordAndWebAuthnLogin;
		this.U2FRegistrations = other.U2FRegistrations;
		this.WebAuthnRegistrations = other.WebAuthnRegistrations;
		this.TOTPKeyEncryptionFormat = other.TOTPKeyEncryptionFormat;
		this.TOTPKey = other.TOTPKey;
		this.IPWhitelist = other.IPWhitelist;
	}

}
}
