// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AmazonAWSVirtualStorageRoleSettings</c>
/// </summary>
public class AmazonAWSVirtualStorageRoleSettings {

	[JsonPropertyName("MasterBucket")]
	public string MasterBucket { get; set; } = string.Empty;

	[JsonPropertyName("AccessKey")]
	public string AccessKey { get; set; } = string.Empty;

	[JsonPropertyName("SecretKey")]
	public string SecretKey { get; set; } = string.Empty;

	[JsonPropertyName("UseObjectLock")]
	public bool UseObjectLock { get; set; }

	[JsonPropertyName("ObjectLockDays")]
	public long ObjectLockDays { get; set; }

	[JsonPropertyName("RemoveDeleted")]
	public bool RemoveDeleted { get; set; }

	public AmazonAWSVirtualStorageRoleSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AmazonAWSVirtualStorageRoleSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AmazonAWSVirtualStorageRoleSettings>(jsStr);
	}

}
}
