// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AuthenticationRoleOptions</c>
/// </summary>
public class AuthenticationRoleOptions {
	public bool RoleEnabled { get; set; }
	public long DatabaseCheckLevel { get; set; }
	public bool GenerateMissedBackupEvents { get; set; }
	public long NoMissedBackupEventsBefore { get; set; }
	public bool GenerateScheduledEmails { get; set; }
	public long PruneLogsAfterDays { get; set; }
	public List<RemoteStorageOption> RemoteStorage { get; set; } = new List<RemoteStorageOption>();
	public List<ReplicaServer> ReplicateTo { get; set; } = new List<ReplicaServer>();
	public GlobalOverrideOptions GlobalOverrides { get; set; } = new GlobalOverrideOptions();

	public AuthenticationRoleOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AuthenticationRoleOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AuthenticationRoleOptions>(jsStr);
	}

}
}
