// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>AzureDestinationLocation</c>
/// </summary>
public class AzureDestinationLocation {
	public string AZBAccountName { get; set; } = string.Empty;
	public string AZBAccountKey { get; set; } = string.Empty;
	public string AZBContainer { get; set; } = string.Empty;
	public string AZBRealm { get; set; } = string.Empty;
	public string AZBPrefix { get; set; } = string.Empty;

	public AzureDestinationLocation(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public AzureDestinationLocation FromJson(string jsStr) {
		return JsonSerializer.Deserialize<AzureDestinationLocation>(jsStr);
	}

}
}
