// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>B2VirtualStorageRoleSettings</c>
/// </summary>
public class B2VirtualStorageRoleSettings {
	public string MasterBucket { get; set; } = "";
	public string KeyID { get; set; } = "";
	public string AppKey { get; set; } = "";
	public bool HideDeletedFiles { get; set; }

	public B2VirtualStorageRoleSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public B2VirtualStorageRoleSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<B2VirtualStorageRoleSettings>(jsStr);
	}

}
}
