// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupJobAdvancedOptions</c>
/// </summary>
public class BackupJobAdvancedOptions {
	public bool SkipAlreadyRunning { get; set; }
	//If Zero: disabled
	public long StopAfter { get; set; }
	//If Zero: disabled
	public long LimitVaultSpeedBps { get; set; }
	//Default disabled
	public bool ReduceDiskConcurrency { get; set; }
	//Default disabled
	public bool UseOnDiskIndexes { get; set; }
	//Default disabled
	public bool AllowZeroFilesSuccess { get; set; }
	//If Zero: default Automatic (BACKUPJOBAUTORETENTION_AUTOMATIC)
	public long AutoRetentionLevel { get; set; }

	public BackupJobAdvancedOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupJobAdvancedOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupJobAdvancedOptions>(jsStr);
	}

}
}
