// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupRuleEventTriggers</c>
/// </summary>
public class BackupRuleEventTriggers {

	[JsonPropertyName("OnPCBoot")]
	//The "When PC Starts" option
	public bool OnPCBoot { get; set; }

	[JsonPropertyName("OnPCBootIfLastJobMissed")]
	//The "If the last job was Missed" option. In Comet 23.12.3 and later, this condition is evaluated when the PC starts
	//and/or when the live connection is resumed.
	public bool OnPCBootIfLastJobMissed { get; set; }

	public BackupRuleEventTriggers(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupRuleEventTriggers FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupRuleEventTriggers>(jsStr);
	}

}
}
