// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupJobAdvancedOptions</c> BackupJobAdvancedOptions control additional advanced options for running a
/// backup job. They can be specified as part of a schedule in the BackupRuleConfig type, or supplied immediately when
/// running a job.
/// </summary>
public class BackupJobAdvancedOptions {

	[JsonPropertyName("SkipAlreadyRunning")]
	public bool SkipAlreadyRunning { get; set; }

	[JsonPropertyName("StopAfter")]
	//If Zero: disabled
	public long StopAfter { get; set; }

	[JsonPropertyName("LimitVaultSpeedBps")]
	//If Zero: disabled
	public long LimitVaultSpeedBps { get; set; }

	[JsonPropertyName("ReduceDiskConcurrency")]
	//Default disabled
	public bool ReduceDiskConcurrency { get; set; }

	[JsonPropertyName("UseOnDiskIndexes")]
	//Default disabled
	public bool UseOnDiskIndexes { get; set; }

	[JsonPropertyName("AllowZeroFilesSuccess")]
	//Default disabled
	public bool AllowZeroFilesSuccess { get; set; }

	[JsonPropertyName("AutoRetentionLevel")]
	//If Zero: default Automatic (BACKUPJOBAUTORETENTION_AUTOMATIC)
	public long AutoRetentionLevel { get; set; }

	public BackupJobAdvancedOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupJobAdvancedOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupJobAdvancedOptions>(jsStr);
	}

}
}
