// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupRuleConfig</c> A backup rule connects one source Protected Item and one destination Storage Vault,
/// with multiple time schedules or event triggers
/// </summary>
public class BackupRuleConfig {
	public string Description { get; set; } = "";
	public long CreateTime { get; set; }
	public long ModifyTime { get; set; }
	public List<string> PreExec { get; set; } = new List<string>();
	public List<string> ThawExec { get; set; } = new List<string>();
	public List<string> PostExec { get; set; } = new List<string>();
	public string Source { get; set; } = "";
	public string Destination { get; set; } = "";
	public bool SkipAlreadyRunning { get; set; }
	public long StopAfter { get; set; }
	public long LimitVaultSpeedBps { get; set; }
	public bool ReduceDiskConcurrency { get; set; }
	public bool UseOnDiskIndexes { get; set; }
	public bool AllowZeroFilesSuccess { get; set; }
	public long AutoRetentionLevel { get; set; }
	public List<ScheduleConfig> Schedules { get; set; } = new List<ScheduleConfig>();
	public BackupRuleEventTriggers EventTriggers { get; set; } = new BackupRuleEventTriggers();

	public BackupRuleConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupRuleConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupRuleConfig>(jsStr);
	}

	public BackupJobAdvancedOptions GetEmbeddedBackupJobAdvancedOptions() => new BackupJobAdvancedOptions {
		SkipAlreadyRunning = this.SkipAlreadyRunning,
		StopAfter = this.StopAfter,
		LimitVaultSpeedBps = this.LimitVaultSpeedBps,
		ReduceDiskConcurrency = this.ReduceDiskConcurrency,
		UseOnDiskIndexes = this.UseOnDiskIndexes,
		AllowZeroFilesSuccess = this.AllowZeroFilesSuccess,
		AutoRetentionLevel = this.AutoRetentionLevel,
	};

	public void SetEmbeddedBackupJobAdvancedOptions(BackupJobAdvancedOptions other){
		this.SkipAlreadyRunning = other.SkipAlreadyRunning;
		this.StopAfter = other.StopAfter;
		this.LimitVaultSpeedBps = other.LimitVaultSpeedBps;
		this.ReduceDiskConcurrency = other.ReduceDiskConcurrency;
		this.UseOnDiskIndexes = other.UseOnDiskIndexes;
		this.AllowZeroFilesSuccess = other.AllowZeroFilesSuccess;
		this.AutoRetentionLevel = other.AutoRetentionLevel;
	}

}
}
