// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupJobDetail</c>
/// </summary>
public class BackupJobDetail {
	public string GUID { get; set; } = string.Empty;
	public string Username { get; set; } = string.Empty;
	public ulong Classification { get; set; }
	public ulong Status { get; set; }
	public long StartTime { get; set; }
	public long EndTime { get; set; }
	public string SourceGUID { get; set; } = string.Empty;
	public string DestinationGUID { get; set; } = string.Empty;
	public string DeviceID { get; set; } = string.Empty;
	public string SnapshotID { get; set; } = string.Empty;
	public string ClientVersion { get; set; } = string.Empty;
	public long TotalDirectories { get; set; }
	public long TotalFiles { get; set; }
	public long TotalSize { get; set; }
	public long TotalChunks { get; set; }
	public long UploadSize { get; set; }
	public long DownloadSize { get; set; }
	public long TotalVmCount { get; set; }
	public long TotalMailsCount { get; set; }
	public long TotalSitesCount { get; set; }
	public long TotalAccountsCount { get; set; }
	public long TotalLicensedMailsCount { get; set; }
	public long TotalUnlicensedMailsCount { get; set; }
	public string CancellationID { get; set; } = string.Empty;
	public BackupJobProgress Progress { get; set; }
	public SizeMeasurement DestinationSizeStart { get; set; }
	public SizeMeasurement DestinationSizeEnd { get; set; }

	public BackupJobDetail(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupJobDetail FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupJobDetail>(jsStr);
	}

}
}
