// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupRuleEventTriggers</c>
/// </summary>
public class BackupRuleEventTriggers {
	public bool OnPCBoot { get; set; }
	public bool OnPCBootIfLastJobMissed { get; set; }

	public BackupRuleEventTriggers(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupRuleEventTriggers FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupRuleEventTriggers>(jsStr);
	}

}
}
