// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BackupJobProgress</c>
/// </summary>
public class BackupJobProgress {
	public long Counter { get; set; }
	public long SentTime { get; set; }
	//The typo is preserved for backwards-compatibility reasons.
	public long RecievedTime { get; set; }
	public long BytesDone { get; set; }
	public long ItemsDone { get; set; }

	public BackupJobProgress(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BackupJobProgress FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BackupJobProgress>(jsStr);
	}

}
}
