// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BrowseVMwareDatacentersResponse</c> BrowseVMwareDatacentersResponse contains a list of VMware Datacenters
/// when remotely browsing a VMware vSphere connection.
/// </summary>
public class BrowseVMwareDatacentersResponse {

	[JsonPropertyName("Status")]
	//If the operation was successful, the status will be in the 200-299 range.
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("Datacenters")]
	public List<VMwareDatacenterInfo> Datacenters { get; set; }

	public BrowseVMwareDatacentersResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BrowseVMwareDatacentersResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BrowseVMwareDatacentersResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
