// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BrowseVSSResponse</c>
/// </summary>
public class BrowseVSSResponse {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public Dictionary<string, VSSWriterInfo> VSSWriters { get; set; } = new Dictionary<string, VSSWriterInfo>();

	public BrowseVSSResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BrowseVSSResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BrowseVSSResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
