// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>BucketProperties</c>
/// </summary>
public class BucketProperties {

	[JsonPropertyName("OrganizationID")]
	public string OrganizationID { get; set; } = string.Empty;

	[JsonPropertyName("CreateTime")]
	//Unix timestamp, in seconds.
	public long CreateTime { get; set; }

	[JsonPropertyName("ReadWriteKeyFormat")]
	//One of the PASSWORD_FORMAT_ constants
	public long ReadWriteKeyFormat { get; set; }

	[JsonPropertyName("ReadWriteKey")]
	public string ReadWriteKey { get; set; } = string.Empty;

	[JsonPropertyName("Size")]
	public SizeMeasurement Size { get; set; }

	public BucketProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public BucketProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<BucketProperties>(jsStr);
	}

}
}
