// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ConstellationCheckReport</c>
/// </summary>
public class ConstellationCheckReport {

	[JsonPropertyName("CheckStarted")]
	//Unix timestamp in seconds
	public long CheckStarted { get; set; }

	[JsonPropertyName("CheckCompleted")]
	//Unix timestamp in seconds
	public long CheckCompleted { get; set; }

	[JsonPropertyName("Usage")]
	public Dictionary<string, BucketUsageInfo> Usage { get; set; }

	public ConstellationCheckReport(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ConstellationCheckReport FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ConstellationCheckReport>(jsStr);
	}

}
}
