// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ConstellationStats</c>
/// </summary>
public class ConstellationStats {
	public long LastCheckStart { get; set; }
	public long TotalChecksStarted { get; set; }
	public long TotalBucketsDeleted { get; set; }
	public long ChecksCurrentlyActive { get; set; }

	public ConstellationStats(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ConstellationStats FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ConstellationStats>(jsStr);
	}

}
}
