// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ConstellationStatusAPIResponse</c>
/// </summary>
public class ConstellationStatusAPIResponse {

	[JsonPropertyName("DeletionEnabled")]
	public bool DeletionEnabled { get; set; }

	[JsonPropertyName("Targets")]
	public List<string> Targets { get; set; }

	[JsonPropertyName("TargetNames")]
	public List<string> TargetNames { get; set; }

	[JsonPropertyName("Stats")]
	public ConstellationStats Stats { get; set; }

	public ConstellationStatusAPIResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ConstellationStatusAPIResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ConstellationStatusAPIResponse>(jsStr);
	}

}
}
