// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ContentMeasurement</c>
/// </summary>
public class ContentMeasurement {

	[JsonPropertyName("MeasureStarted")]
	//Unix timestamp in seconds
	public long MeasureStarted { get; set; }

	[JsonPropertyName("MeasureCompleted")]
	//Unix timestamp in seconds
	public long MeasureCompleted { get; set; }

	[JsonPropertyName("Components")]
	public List<ContentMeasurementComponent> Components { get; set; }

	public ContentMeasurement(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ContentMeasurement FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ContentMeasurement>(jsStr);
	}

}
}
