// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ContentMeasurementComponent</c>
/// </summary>
public class ContentMeasurementComponent {
	public long Bytes { get; set; }
	public List<string> UsedBy { get; set; }

	public ContentMeasurementComponent(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ContentMeasurementComponent FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ContentMeasurementComponent>(jsStr);
	}

}
}
