// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ContentMeasurement</c>
/// </summary>
public class ContentMeasurement {
	public long MeasureStarted { get; set; }
	public long MeasureCompleted { get; set; }
	public List<ContentMeasurementComponent> Components { get; set; } = new List<ContentMeasurementComponent>();

	public ContentMeasurement(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ContentMeasurement FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ContentMeasurement>(jsStr);
	}

}
}
