// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>CountJobsResponse</c>
/// </summary>
public class CountJobsResponse {

	[JsonPropertyName("Count")]
	public long Count { get; set; }

	public CountJobsResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public CountJobsResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<CountJobsResponse>(jsStr);
	}

}
}
