// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>CustomRemoteBucketSettings</c>
/// </summary>
public class CustomRemoteBucketSettings {

	[JsonPropertyName("URL")]
	public string URL { get; set; } = string.Empty;

	[JsonPropertyName("CustomHeaders")]
	public Dictionary<string, string> CustomHeaders { get; set; }

	public CustomRemoteBucketSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public CustomRemoteBucketSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<CustomRemoteBucketSettings>(jsStr);
	}

}
}
