// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DestinationStatistics</c>
/// </summary>
public class DestinationStatistics {
	public SizeMeasurement ClientProvidedSize { get; set; }
	public ContentMeasurement ClientProvidedContent { get; set; }
	public string LastSuccessfulDeepVerify_GUID { get; set; } = string.Empty;
	//Unix timestamp in seconds
	public long LastSuccessfulDeepVerify_StartTime { get; set; }
	//Unix timestamp in seconds
	public long LastSuccessfulDeepVerify_EndTime { get; set; }

	public DestinationStatistics(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DestinationStatistics FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DestinationStatistics>(jsStr);
	}

}
}
