// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DeviceConfig</c>
/// </summary>
public class DeviceConfig {
	public string FriendlyName { get; set; } = "";
	public long RegistrationTime { get; set; }
	public OSInfo PlatformVersion { get; set; } = new OSInfo();
	public Dictionary<string, SourceBasicInfo> Sources { get; set; } = new Dictionary<string, SourceBasicInfo>();
	public string DeviceTimezone { get; set; } = "";

	public DeviceConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DeviceConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DeviceConfig>(jsStr);
	}

}
}
