// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DiskDrive</c>
/// </summary>
public class DiskDrive {

	[JsonPropertyName("ID")]
	public string ID { get; set; } = string.Empty;

	[JsonPropertyName("DeviceName")]
	public string DeviceName { get; set; } = string.Empty;

	[JsonPropertyName("Caption")]
	public string Caption { get; set; } = string.Empty;

	[JsonPropertyName("Model")]
	public string Model { get; set; } = string.Empty;

	[JsonPropertyName("SerialNumber")]
	public string SerialNumber { get; set; } = string.Empty;

	[JsonPropertyName("Size")]
	//Bytes
	public long Size { get; set; }

	[JsonPropertyName("Partitions")]
	public List<Partition> Partitions { get; set; }

	[JsonPropertyName("DeviceParents")]
	//For physical disks, this array will be empty. For virtual disks, RAID devices or Linux DM devices, this array may
	//contain the DeviceName of the parent device.
	public List<string> DeviceParents { get; set; }

	[JsonPropertyName("Flags")]
	//See WINDISKFLAG_ constants
	public long Flags { get; set; }

	[Obsolete("Deprecated since Comet version 24.6.x This value is reported from the disk driver if available. Otherwise emulates a value based on modern LBA addressing. The field value is not used.")]

	[JsonPropertyName("Cylinders")]
	public long Cylinders { get; set; }

	[Obsolete("Deprecated since Comet version 24.6.x This value is reported from the disk driver if available. Otherwise emulates a value based on modern LBA addressing. The field value is not used.")]

	[JsonPropertyName("Heads")]
	public long Heads { get; set; }

	[Obsolete("Deprecated since Comet version 24.6.x This value is reported from the disk driver if available. Otherwise emulates a value based on modern LBA addressing. The field value is not used.")]

	[JsonPropertyName("Sectors")]
	public long Sectors { get; set; }

	[JsonPropertyName("SectorSize")]
	public long SectorSize { get; set; }

	public DiskDrive(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DiskDrive FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DiskDrive>(jsStr);
	}

}
}
