// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DiskDrive</c>
/// </summary>
public class DiskDrive {
	public string ID { get; set; } = string.Empty;
	public string DeviceName { get; set; } = string.Empty;
	public string Caption { get; set; } = string.Empty;
	public string Model { get; set; } = string.Empty;
	public string SerialNumber { get; set; } = string.Empty;
	public long Size { get; set; }
	public List<Partition> Partitions { get; set; }
	public long Flags { get; set; }
	public long Cylinders { get; set; }
	public long Heads { get; set; }
	public long Sectors { get; set; }
	public long SectorSize { get; set; }

	public DiskDrive(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DiskDrive FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DiskDrive>(jsStr);
	}

}
}
