// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DispatcherAdminSourcesResponse</c>
/// </summary>
public class DispatcherAdminSourcesResponse {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public Dictionary<string, string> ImportSources { get; set; } = new Dictionary<string, string>();

	public DispatcherAdminSourcesResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DispatcherAdminSourcesResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DispatcherAdminSourcesResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
