// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DispatcherListSnapshotVirtualMachinesResponse</c>
/// Since Version : 24.12.x
/// </summary>
public class DispatcherListSnapshotVirtualMachinesResponse {

	[JsonPropertyName("Status")]
	//If the operation was successful, the status will be in the 200-299 range.
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("VMs")]
	public List<VMInfo> VMs { get; set; }

	public DispatcherListSnapshotVirtualMachinesResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DispatcherListSnapshotVirtualMachinesResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DispatcherListSnapshotVirtualMachinesResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

	public VMInfoList GetEmbeddedVMInfoList() => new VMInfoList {
		VMs = this.VMs,
	};

	public void SetEmbeddedVMInfoList(VMInfoList other){
		this.VMs = other.VMs;
	}

}
}
