// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>DispatcherVaultSnapshotsResponse</c>
/// </summary>
public class DispatcherVaultSnapshotsResponse {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public List<VaultSnapshot> Snapshots { get; set; } = new List<VaultSnapshot>();

	public DispatcherVaultSnapshotsResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public DispatcherVaultSnapshotsResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<DispatcherVaultSnapshotsResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
