// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EDBFileInfo</c>
/// </summary>
public class EDBFileInfo {
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("Guid")]
	public string GUID { get; set; } = string.Empty;
	public string ServerName { get; set; } = string.Empty;
	public bool CircularLoggingEnabled { get; set; }

	public EDBFileInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EDBFileInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EDBFileInfo>(jsStr);
	}

}
}
