// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EmailReportingOption</c>
/// </summary>
public class EmailReportingOption {
	public EmailReportConfig EmailReportConfig { get; set; } = new EmailReportConfig();
	public string LanguageCode { get; set; } = "";
	public string LocalTimezone { get; set; } = "";
	public List<string> Recipients { get; set; } = new List<string>();

	public EmailReportingOption(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EmailReportingOption FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EmailReportingOption>(jsStr);
	}

}
}
