// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EmailReportGeneratedPreview</c>
/// </summary>
public class EmailReportGeneratedPreview {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public string From { get; set; } = "";
	public List<string> To { get; set; } = new List<string>();
	public string EmailSubject { get; set; } = "";
	public string EmailBodyHTML { get; set; } = "";
	public string EmailBodyPlaintext { get; set; } = "";

	public EmailReportGeneratedPreview(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EmailReportGeneratedPreview FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EmailReportGeneratedPreview>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
