// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EmailReportConfig</c>
/// </summary>
public class EmailReportConfig {
	public long ReportType { get; set; }
	public List<ScheduleConfig> SummaryFrequency { get; set; } = new List<ScheduleConfig>();
	public TimeSpan TimeSpan { get; set; } = new TimeSpan();
	public SearchClause Filter { get; set; } = new SearchClause();

	public EmailReportConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EmailReportConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EmailReportConfig>(jsStr);
	}

}
}
