// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EmailOptions</c>
/// </summary>
public class EmailOptions {
	public string FromEmail { get; set; } = "";
	public string FromName { get; set; } = "";
	public string Mode { get; set; } = "";
	public List<EmailReportingOption> EmailReportingOptions { get; set; } = new List<EmailReportingOption>();
	public string SMTPHost { get; set; } = "";
	public long SMTPPort { get; set; }
	public string SMTPUsername { get; set; } = "";
	public string SMTPPassword { get; set; } = "";
	public bool SMTPAllowInvalidCertificate { get; set; }
	public bool SMTPAllowUnencrypted { get; set; }

	public EmailOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EmailOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EmailOptions>(jsStr);
	}

	public AdminEmailOptions GetEmbeddedAdminEmailOptions() => new AdminEmailOptions {
		FromEmail = this.FromEmail,
		FromName = this.FromName,
	};

	public void SetEmbeddedAdminEmailOptions(AdminEmailOptions other){
		this.FromEmail = other.FromEmail;
		this.FromName = other.FromName;
	}

}
}
