// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>EmailOptions</c>
/// </summary>
public class EmailOptions {

	[JsonPropertyName("FromEmail")]
	public string FromEmail { get; set; } = string.Empty;

	[JsonPropertyName("FromName")]
	public string FromName { get; set; } = string.Empty;

	[JsonPropertyName("Mode")]
	//One of the EMAIL_DELIVERY_ constants
	public string Mode { get; set; } = string.Empty;

	[JsonPropertyName("EmailReportingOptions")]
	public List<EmailReportingOption> EmailReportingOptions { get; set; }

	[JsonPropertyName("SMTPHost")]
	public string SMTPHost { get; set; } = string.Empty;

	[JsonPropertyName("SMTPPort")]
	public long SMTPPort { get; set; }

	[JsonPropertyName("SMTPUsername")]
	public string SMTPUsername { get; set; } = string.Empty;

	[JsonPropertyName("SMTPPassword")]
	public string SMTPPassword { get; set; } = string.Empty;

	[JsonPropertyName("SMTPAllowInvalidCertificate")]
	public bool SMTPAllowInvalidCertificate { get; set; }

	[JsonPropertyName("SMTPAllowUnencrypted")]
	public bool SMTPAllowUnencrypted { get; set; }

	[JsonPropertyName("SMTPCustomEhlo")]
	//Override the HELO/EHLO hostname for SMTP or MX Direct modes. If blank, uses system default HELO/EHLO hostname.
	public string SMTPCustomEhlo { get; set; } = string.Empty;

	public EmailOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public EmailOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<EmailOptions>(jsStr);
	}

	public AdminEmailOptions GetEmbeddedAdminEmailOptions() => new AdminEmailOptions {
		FromEmail = this.FromEmail,
		FromName = this.FromName,
	};

	public void SetEmbeddedAdminEmailOptions(AdminEmailOptions other){
		this.FromEmail = other.FromEmail;
		this.FromName = other.FromName;
	}

}
}
