// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ExternalLDAPAuthenticationSourceServer</c>
/// </summary>
public class ExternalLDAPAuthenticationSourceServer {
	public string Hostname { get; set; } = "";
	public long Port { get; set; }
	public string SecurityMethod { get; set; } = "";
	public bool AcceptInvalidSSL { get; set; }

	public ExternalLDAPAuthenticationSourceServer(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ExternalLDAPAuthenticationSourceServer FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ExternalLDAPAuthenticationSourceServer>(jsStr);
	}

}
}
