// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ExternalAuthenticationSourceDisplay</c>
/// </summary>
public class ExternalAuthenticationSourceDisplay {

	[JsonPropertyName("DisplayName")]
	public string DisplayName { get; set; } = string.Empty;

	[JsonPropertyName("LoginStartURL")]
	public string LoginStartURL { get; set; } = string.Empty;

	public ExternalAuthenticationSourceDisplay(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ExternalAuthenticationSourceDisplay FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ExternalAuthenticationSourceDisplay>(jsStr);
	}

}
}
