// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ExternalLDAPAuthenticationSourceSettings</c>
/// </summary>
public class ExternalLDAPAuthenticationSourceSettings {

	[JsonPropertyName("Hostname")]
	public string Hostname { get; set; } = string.Empty;

	[JsonPropertyName("Port")]
	public long Port { get; set; }

	[JsonPropertyName("SecurityMethod")]
	//One of the LDAPSECURITYMETHOD_ constants (e.g. "plain" / "ldaps" / "starttls")
	public string SecurityMethod { get; set; } = string.Empty;

	[JsonPropertyName("AcceptInvalidSSL")]
	public bool AcceptInvalidSSL { get; set; }

	[JsonPropertyName("FallbackServers")]
	public List<ExternalLDAPAuthenticationSourceServer> FallbackServers { get; set; }

	[JsonPropertyName("BindUser")]
	public string BindUser { get; set; } = string.Empty;

	[JsonPropertyName("BindPassword")]
	public string BindPassword { get; set; } = string.Empty;

	[JsonPropertyName("SearchDN")]
	public string SearchDN { get; set; } = string.Empty;

	[JsonPropertyName("SearchFilter")]
	public string SearchFilter { get; set; } = string.Empty;

	public ExternalLDAPAuthenticationSourceSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ExternalLDAPAuthenticationSourceSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ExternalLDAPAuthenticationSourceSettings>(jsStr);
	}

	public ExternalLDAPAuthenticationSourceServer GetEmbeddedExternalLDAPAuthenticationSourceServer() => new ExternalLDAPAuthenticationSourceServer {
		Hostname = this.Hostname,
		Port = this.Port,
		SecurityMethod = this.SecurityMethod,
		AcceptInvalidSSL = this.AcceptInvalidSSL,
	};

	public void SetEmbeddedExternalLDAPAuthenticationSourceServer(ExternalLDAPAuthenticationSourceServer other){
		this.Hostname = other.Hostname;
		this.Port = other.Port;
		this.SecurityMethod = other.SecurityMethod;
		this.AcceptInvalidSSL = other.AcceptInvalidSSL;
	}

}
}
