// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ExternalAuthenticationSourceResponse</c>
/// </summary>
public class ExternalAuthenticationSourceResponse {

	[JsonPropertyName("Status")]
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("ID")]
	public string ID { get; set; } = string.Empty;

	[JsonPropertyName("Source")]
	public ExternalAuthenticationSource Source { get; set; }

	public ExternalAuthenticationSourceResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ExternalAuthenticationSourceResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ExternalAuthenticationSourceResponse>(jsStr);
	}

}
}
