// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>GetProfileAndHashResponseMessage</c>
/// </summary>
public class GetProfileAndHashResponseMessage {

	[JsonPropertyName("Status")]
	//If the operation was successful, the status will be in the 200-299 range.
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("ProfileHash")]
	//A hash identifier for the current state of the user's profile. If you supply this in the AdminSetUserProfileHash API,
	//the server can safely reject your change if another change has happened concurrently. This allows you to retry the
	//request.
	public string ProfileHash { get; set; } = string.Empty;

	[JsonPropertyName("Profile")]
	public UserProfileConfig Profile { get; set; }

	public GetProfileAndHashResponseMessage(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public GetProfileAndHashResponseMessage FromJson(string jsStr) {
		return JsonSerializer.Deserialize<GetProfileAndHashResponseMessage>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
