// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>GetSharedStorageQuotaResponse</c>
/// </summary>
public class GetSharedStorageQuotaResponse {

	[JsonPropertyName("Status")]
	//If the operation was successful, the status will be in the 200-299 range.
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("SharedStorageQuota")]
	public SharedStorageQuota SharedStorageQuota { get; set; }

	[JsonPropertyName("SharedStorageQuotaHash")]
	public string SharedStorageQuotaHash { get; set; } = string.Empty;

	[JsonPropertyName("CurrentUsage")]
	//Bytes
	public long CurrentUsage { get; set; }

	public GetSharedStorageQuotaResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public GetSharedStorageQuotaResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<GetSharedStorageQuotaResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
