// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>GetUserGroupWithUsersResponse</c>
/// </summary>
public class GetUserGroupWithUsersResponse {

	[JsonPropertyName("UserGroup")]
	public UserGroup UserGroup { get; set; }

	[JsonPropertyName("Users")]
	public Dictionary<string, UserProfileConfig> Users { get; set; }

	public GetUserGroupWithUsersResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public GetUserGroupWithUsersResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<GetUserGroupWithUsersResponse>(jsStr);
	}

}
}
