// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>GetUserGroupResponse</c>
/// </summary>
public class GetUserGroupResponse {

	[JsonPropertyName("UserGroup")]
	public UserGroup UserGroup { get; set; }

	[JsonPropertyName("UserGroupHash")]
	public string UserGroupHash { get; set; } = string.Empty;

	public GetUserGroupResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public GetUserGroupResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<GetUserGroupResponse>(jsStr);
	}

}
}
