// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>GlobalOverrideOptions</c>
/// </summary>
public class GlobalOverrideOptions {
	public ulong RandomDelaySecs { get; set; }

	public GlobalOverrideOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public GlobalOverrideOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<GlobalOverrideOptions>(jsStr);
	}

}
}
