// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>HTTPConnectorOptions</c>
/// </summary>
public class HTTPConnectorOptions {

	[JsonPropertyName("ListenAddress")]
	public string ListenAddress__DONOTUSEDIRECTLY { get; set; } = string.Empty;
	public string SSLCertPath { get; set; } = string.Empty;
	public string SSLIntermediate { get; set; } = string.Empty;
	public string SSLCertKey { get; set; } = string.Empty;
	public string AutoSSLDomains { get; set; } = string.Empty;
	public string SSLPfxPath { get; set; } = string.Empty;
	public string SSLPfxPassword { get; set; } = string.Empty;

	public HTTPConnectorOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public HTTPConnectorOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<HTTPConnectorOptions>(jsStr);
	}

}
}
