// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>HyperVRestoreTargetOptions</c>
/// </summary>
public class HyperVRestoreTargetOptions {

	[JsonPropertyName("DiskStoragePath")]
	public string DiskStoragePath { get; set; } = string.Empty;

	public HyperVRestoreTargetOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public HyperVRestoreTargetOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<HyperVRestoreTargetOptions>(jsStr);
	}

}
}
