// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ImpossibleCloudPartnerTemplateSettings</c>
/// Since Version : 24.3.1
/// </summary>
public class ImpossibleCloudPartnerTemplateSettings {

	[JsonPropertyName("Region")]
	//Optional. The region for your Partner console and for provisioning new buckets. If blank, uses the default region for
	//Impossible Cloud (eu-central-2).
	public string Region { get; set; } = string.Empty;

	[JsonPropertyName("AccessKey")]
	public string AccessKey { get; set; } = string.Empty;

	public ImpossibleCloudPartnerTemplateSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ImpossibleCloudPartnerTemplateSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ImpossibleCloudPartnerTemplateSettings>(jsStr);
	}

}
}
