// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>InstallCreds</c>
/// </summary>
public class InstallCreds {
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public string Server { get; set; } = string.Empty;
	public bool AutoLogin { get; set; }

	public InstallCreds(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public InstallCreds FromJson(string jsStr) {
		return JsonSerializer.Deserialize<InstallCreds>(jsStr);
	}

}
}
