// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>JobEntry</c> JobEntry is a single entry within a job report.
/// </summary>
public class JobEntry {
	public long Time { get; set; }
	public string Severity { get; set; } = string.Empty;
	public string Message { get; set; } = string.Empty;

	public JobEntry(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public JobEntry FromJson(string jsStr) {
		return JsonSerializer.Deserialize<JobEntry>(jsStr);
	}

}
}
