// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>LicenseOptions</c>
/// </summary>
public class LicenseOptions {
	public string Email { get; set; } = "";
	public string SerialNumber { get; set; } = "";

	public LicenseOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public LicenseOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<LicenseOptions>(jsStr);
	}

}
}
