// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>LicenseLimits</c>
/// </summary>
public class LicenseLimits {

	[JsonPropertyName("deviceCount")]
	public long DeviceCount { get; set; }

	[JsonPropertyName("boosterCount")]
	public Dictionary<string, long> BoosterCount { get; set; }

	public LicenseLimits(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public LicenseLimits FromJson(string jsStr) {
		return JsonSerializer.Deserialize<LicenseLimits>(jsStr);
	}

}
}
