// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>LiveUserConnection</c>
/// </summary>
public class LiveUserConnection {
	public string Username { get; set; } = string.Empty;
	public string DeviceID { get; set; } = string.Empty;
	public string ReportedVersion { get; set; } = string.Empty;
	public string ReportedPlatform { get; set; } = string.Empty;
	public OSInfo ReportedPlatformVersion { get; set; }
	public string DeviceTimeZone { get; set; } = string.Empty;
	public string IPAddress { get; set; } = string.Empty;
	public long ConnectionTime { get; set; }
	public bool AllowsFilenames { get; set; }

	public LiveUserConnection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public LiveUserConnection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<LiveUserConnection>(jsStr);
	}

}
}
