// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>LocalDestinationLocation</c>
/// </summary>
public class LocalDestinationLocation {
	public string LocalcopyPath { get; set; } = "";
	public string LocalcopyWinSMBUsername { get; set; } = "";
	public string LocalcopyWinSMBPassword { get; set; } = "";
	public ulong LocalcopyWinSMBPasswordFormat { get; set; }

	public LocalDestinationLocation(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public LocalDestinationLocation FromJson(string jsStr) {
		return JsonSerializer.Deserialize<LocalDestinationLocation>(jsStr);
	}

}
}
