// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>LoginProtectionOptions</c>
/// </summary>
public class LoginProtectionOptions {

	[JsonPropertyName("Enabled")]
	//Enable this feature to block repeated failed login attempts to the Comet Server.
	public bool Enabled { get; set; }

	[JsonPropertyName("FailureThreshold")]
	//The number of failed attempts before a cooldown is applied. If the feature is enabled, should be at least 1.
	public long FailureThreshold { get; set; }

	[JsonPropertyName("CooldownSeconds")]
	//The duration to block requests, in seconds. If the feature is enabled, should be at least 1 second.
	public long CooldownSeconds { get; set; }

	public LoginProtectionOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public LoginProtectionOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<LoginProtectionOptions>(jsStr);
	}

}
}
