// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>MacOSCodeSignProperties</c>
/// </summary>
public class MacOSCodeSignProperties {
	public long Level { get; set; }
	public bool SignLocally { get; set; }
	public SSHConnection SSHServer { get; set; } = new SSHConnection();
	public string CertificateName { get; set; } = "";
	public string AppCertificateName { get; set; } = "";
	public string AppleID { get; set; } = "";
	public string AppleIDPass { get; set; } = "";
	public ulong AppleIDPassFormat { get; set; }
	public string CertificateFile { get; set; } = "";
	public string AppCertificateFile { get; set; } = "";
	public string PfxFilePassword { get; set; } = "";
	public ulong PfxFilePasswordFormat { get; set; }
	public string NotaryAPIIssuerID { get; set; } = "";
	public string NotaryAPIKeyID { get; set; } = "";
	public string NotaryAPIKeyFile { get; set; } = "";

	public MacOSCodeSignProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public MacOSCodeSignProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<MacOSCodeSignProperties>(jsStr);
	}

}
}
