// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>MongoDBConnection</c>
/// </summary>
public class MongoDBConnection {
	public string Server { get; set; } = string.Empty;
	public long Port { get; set; }
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public string AuthenticationDB { get; set; } = string.Empty;

	[Obsolete("Deprecated since Comet version 22.12.3")]
	public string MongoShellPath { get; set; } = string.Empty;
	public string MongodumpPath { get; set; } = string.Empty;
	public string ReadPreference { get; set; } = string.Empty;
	public bool UseReplica { get; set; }
	public string ReplicaName { get; set; } = string.Empty;
	public List<string> ReplicaMembers { get; set; }
	public bool UseSSL { get; set; }
	public string ClientSSLPEMPath { get; set; } = string.Empty;
	public string ServerSSLPEMPath { get; set; } = string.Empty;
	public string SSLClientKeyPassword { get; set; } = string.Empty;
	public bool AllowInvalidCertificate { get; set; }
	public bool AllowInvalidHostname { get; set; }
	public bool UseSSH { get; set; }
	public SSHConnection SSHConnection { get; set; }

	public MongoDBConnection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public MongoDBConnection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<MongoDBConnection>(jsStr);
	}

}
}
