// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>MSSQLLoginArgs</c>
/// </summary>
public class MSSQLLoginArgs {
	public string Instance { get; set; } = string.Empty;
	public string AuthMode { get; set; } = string.Empty;
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public bool MethodIsOledb32Bit { get; set; }
	//If this MSSQLLoginArgs structure is used for a restore job (RestoreJobAdvancedOptions) using RESTORETYPE_MSSQL, then,
	//this field controls the RECOVERY / NO RECOVERY option state.
	public bool RestoreNoRecovery { get; set; }

	public MSSQLLoginArgs(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public MSSQLLoginArgs FromJson(string jsStr) {
		return JsonSerializer.Deserialize<MSSQLLoginArgs>(jsStr);
	}

}
}
