// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>MySQLConnection</c>
/// </summary>
public class MySQLConnection {
	public string Host { get; set; } = "";
	public string Port { get; set; } = "";
	public string Username { get; set; } = "";
	public string Password { get; set; } = "";
	public bool UseTLS { get; set; }
	public bool TLSSkipVerify { get; set; }
	public string TLSCustomServerCAPath { get; set; } = "";
	public string TLSCustomClientCrtPath { get; set; } = "";
	public string TLSCustomClientKeyPath { get; set; } = "";

	public MySQLConnection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public MySQLConnection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<MySQLConnection>(jsStr);
	}

}
}
