// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>NewBucketDetail</c>
/// </summary>
public class NewBucketDetail {
	public string NewBucketID { get; set; } = string.Empty;
	public string NewBucketKey { get; set; } = string.Empty;

	public NewBucketDetail(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public NewBucketDetail FromJson(string jsStr) {
		return JsonSerializer.Deserialize<NewBucketDetail>(jsStr);
	}

}
}
