// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>NewsEntry</c>
/// </summary>
public class NewsEntry {

	[JsonPropertyName("OrganizationID")]
	public string OrganizationID { get; set; } = string.Empty;

	[JsonPropertyName("DateTime")]
	//Unix timestamp, in seconds.
	public long DateTime { get; set; }

	[JsonPropertyName("TextContent")]
	public string TextContent { get; set; } = string.Empty;

	public NewsEntry(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public NewsEntry FromJson(string jsStr) {
		return JsonSerializer.Deserialize<NewsEntry>(jsStr);
	}

}
}
