// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ObjectLockStorageTemplateSettings</c>
/// </summary>
public class ObjectLockStorageTemplateSettings {

	[Obsolete("Deprecated since Comet version 23.x.x")]

	[JsonPropertyName("UseObjectLock")]
	public bool UseObjectLock_Legacy_DoNotUse { get; set; }

	[JsonPropertyName("ObjectLockMode")]
	//Control whether the resulting Storage Vaults are configured for Object Lock. One of the OBJECT_LOCK_ constants
	public byte ObjectLockMode { get; set; }

	[JsonPropertyName("ObjectLockDays")]
	public long ObjectLockDays { get; set; }

	[JsonPropertyName("RemoveDeleted")]
	//Control whether the "Allow removal of deleted files" checkbox is enabled for Storage Vaults generated from this
	//Storage Template.
	//When configuring a Storage Template from the Comet Server web interface, this field is set automatically for Storage
	//Templates using Object Lock.
	public bool RemoveDeleted { get; set; }

	public ObjectLockStorageTemplateSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ObjectLockStorageTemplateSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ObjectLockStorageTemplateSettings>(jsStr);
	}

}
}
