// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Office365Connection</c>
/// </summary>
public class Office365Connection {

	[JsonPropertyName("FeatureFlag")]
	public string FeatureFlag { get; set; } = string.Empty;

	[JsonPropertyName("Credential")]
	public Office365Credential Credential { get; set; }

	[JsonPropertyName("CustomSetting")]
	public Office365CustomSetting CustomSetting { get; set; }

	[JsonPropertyName("MailboxUniqueMembers")]
	public List<string> MailboxUniqueMembers { get; set; }

	[JsonPropertyName("SiteUniqueMembers")]
	public List<string> SiteUniqueMembers { get; set; }

	[JsonPropertyName("CustomSettingV2")]
	public Office365CustomSettingV2 CustomSettingV2 { get; set; }

	public Office365Connection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Office365Connection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Office365Connection>(jsStr);
	}

}
}
