// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Office365MixedVirtualAccount</c>
/// </summary>
public class Office365MixedVirtualAccount {

	[JsonPropertyName("id")]
	public string ID { get; set; } = string.Empty;
	public long Type { get; set; }
	public string DisplayName { get; set; } = string.Empty;
	public string Mail { get; set; } = string.Empty;
	public string JobTitle { get; set; } = string.Empty;
	public string SiteID { get; set; } = string.Empty;
	public string WebID { get; set; } = string.Empty;
	public string WebURL { get; set; } = string.Empty;
	public string UserPrincipalName { get; set; } = string.Empty;
	public long EnabledServiceOption { get; set; }
	public List<string> Members { get; set; }
	public long ServiceOptions { get; set; }
	public long MemberServiceOptions { get; set; }

	[JsonPropertyName("hasLicense")]
	public bool HasLicense { get; set; }

	public Office365MixedVirtualAccount(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Office365MixedVirtualAccount FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Office365MixedVirtualAccount>(jsStr);
	}

}
}
