// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Office365Connection</c>
/// </summary>
public class Office365Connection {
	public string FeatureFlag { get; set; } = "";
	public Office365Credential Credential { get; set; } = new Office365Credential();
	public Office365CustomSetting CustomSetting { get; set; } = new Office365CustomSetting();
	public List<string> MailboxUniqueMembers { get; set; } = new List<string>();
	public List<string> SiteUniqueMembers { get; set; } = new List<string>();
	public Office365CustomSettingV2 CustomSettingV2 { get; set; } = new Office365CustomSettingV2();

	public Office365Connection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Office365Connection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Office365Connection>(jsStr);
	}

}
}
