// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Office365ObjectInfo</c>
/// </summary>
public class Office365ObjectInfo {

	[JsonPropertyName("GUID")]
	public string GUID { get; set; } = string.Empty;

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("Type")]
	public string Type { get; set; } = string.Empty;

	[JsonPropertyName("Value")]
	//May be an email address or a SharePoint site URL
	public string Value { get; set; } = string.Empty;

	[JsonPropertyName("Members")]
	public List<string> Members { get; set; }

	public Office365ObjectInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Office365ObjectInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Office365ObjectInfo>(jsStr);
	}

}
}
