// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>OidcClaim</c>
/// </summary>
public class OidcClaim {

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("Value")]
	public string Value { get; set; } = string.Empty;

	public OidcClaim(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public OidcClaim FromJson(string jsStr) {
		return JsonSerializer.Deserialize<OidcClaim>(jsStr);
	}

}
}
