// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Organization</c>
/// </summary>
public class Organization {
	public string Name { get; set; } = "";
	public List<string> Hosts { get; set; } = new List<string>();
	public SoftwareBuildRoleOptions SoftwareBuildRole { get; set; } = new SoftwareBuildRoleOptions();
	public BrandingOptions Branding { get; set; } = new BrandingOptions();
	public List<RemoteStorageOption> RemoteStorage { get; set; } = new List<RemoteStorageOption>();
	public ConstellationRoleOptions ConstellationRole { get; set; } = new ConstellationRoleOptions();
	public Dictionary<string, WebhookOption> WebhookOptions { get; set; } = new Dictionary<string, WebhookOption>();
	public List<PSAConfig> PSAConfigs { get; set; } = new List<PSAConfig>();
	public EmailOptions Email { get; set; } = new EmailOptions();
	public bool IsSuspended { get; set; }
	public List<string> ExperimentalOptions { get; set; } = new List<string>();

	public Organization(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Organization FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Organization>(jsStr);
	}

}
}
