// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>OrganizationResponse</c>
/// </summary>
public class OrganizationResponse {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public string ID { get; set; } = "";
	public Organization Organization { get; set; } = new Organization();

	public OrganizationResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public OrganizationResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<OrganizationResponse>(jsStr);
	}

}
}
