// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>OrganizationResponse</c>
/// </summary>
public class OrganizationResponse {

	[JsonPropertyName("Status")]
	public long Status { get; set; }

	[JsonPropertyName("Message")]
	public string Message { get; set; } = string.Empty;

	[JsonPropertyName("ID")]
	public string ID { get; set; } = string.Empty;

	[JsonPropertyName("Organization")]
	public Organization Organization { get; set; }

	public OrganizationResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public OrganizationResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<OrganizationResponse>(jsStr);
	}

}
}
