// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PartitionConflict</c>
/// </summary>
public class PartitionConflict {

	[JsonPropertyName("PartitionA")]
	public string PartitionA { get; set; } = string.Empty;

	[JsonPropertyName("PartitionB")]
	public string PartitionB { get; set; } = string.Empty;

	[JsonPropertyName("Size")]
	public ulong Size { get; set; }

	public PartitionConflict(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PartitionConflict FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PartitionConflict>(jsStr);
	}

}
}
