// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>Partition</c>
/// </summary>
public class Partition {
	public string DeviceName { get; set; } = string.Empty;
	public string Filesystem { get; set; } = string.Empty;
	public string VolumeName { get; set; } = string.Empty;
	public string VolumeGuid { get; set; } = string.Empty;
	public string VolumeSerial { get; set; } = string.Empty;
	public List<string> MountPoints { get; set; }
	public long ReadOffset { get; set; }
	public long Size { get; set; }
	public long UsedSize { get; set; }
	public long Flags { get; set; }
	public long BytesPerFilesystemCluster { get; set; }

	public Partition(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public Partition FromJson(string jsStr) {
		return JsonSerializer.Deserialize<Partition>(jsStr);
	}

}
}
