// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PrivateBrandingProperties</c>
/// </summary>
public class PrivateBrandingProperties {
	public long BuildMode { get; set; }
	public string PathIcoFile { get; set; } = string.Empty;
	public string PathIcnsFile { get; set; } = string.Empty;
	public string PathMenuBarIcnsFile { get; set; } = string.Empty;
	public string PathEulaRtf { get; set; } = string.Empty;
	public string PathTilePng { get; set; } = string.Empty;
	public string PathHeaderImage { get; set; } = string.Empty;
	public string PathAppIconImage { get; set; } = string.Empty;
	public string PackageIdentifier { get; set; } = string.Empty;
	public long WindowsCodeSignMethod { get; set; }
	public string WindowsCodeSignPKCS12FilePath { get; set; } = string.Empty;
	public ulong WindowsCodeSignPKCS12PasswordFormat { get; set; }
	public string WindowsCodeSignPKCS12Password { get; set; } = string.Empty;
	public string WindowsCodeSignPKCS11Engine { get; set; } = string.Empty;
	public string WindowsCodeSignPKCS11Module { get; set; } = string.Empty;

	[Obsolete("Deprecated since Comet version 22.12.7")]
	public string WindowsCodeSignPKCS11Certfile { get; set; } = string.Empty;
	public string WindowsCodeSignPKCS11KeyID { get; set; } = string.Empty;
	public ulong WindowsCodeSignPKCS11PasswordFormat { get; set; }
	public string WindowsCodeSignPKCS11Password { get; set; } = string.Empty;
	public string WindowsCodeSignAzureVaultName { get; set; } = string.Empty;
	public string WindowsCodeSignAzureCertName { get; set; } = string.Empty;
	public string WindowsCodeSignAzureAppID { get; set; } = string.Empty;
	public ulong WindowsCodeSignAzureAppSecretFormat { get; set; }
	public string WindowsCodeSignAzureAppSecret { get; set; } = string.Empty;
	public string WindowsCodeSignAzureTenantID { get; set; } = string.Empty;
	public MacOSCodeSignProperties MacOSCodeSign { get; set; }

	public PrivateBrandingProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PrivateBrandingProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PrivateBrandingProperties>(jsStr);
	}

	public WindowsCodeSignProperties GetEmbeddedWindowsCodeSignProperties() => new WindowsCodeSignProperties {
		WindowsCodeSignMethod = this.WindowsCodeSignMethod,
		WindowsCodeSignPKCS12FilePath = this.WindowsCodeSignPKCS12FilePath,
		WindowsCodeSignPKCS12PasswordFormat = this.WindowsCodeSignPKCS12PasswordFormat,
		WindowsCodeSignPKCS12Password = this.WindowsCodeSignPKCS12Password,
		WindowsCodeSignPKCS11Engine = this.WindowsCodeSignPKCS11Engine,
		WindowsCodeSignPKCS11Module = this.WindowsCodeSignPKCS11Module,
		WindowsCodeSignPKCS11Certfile = this.WindowsCodeSignPKCS11Certfile,
		WindowsCodeSignPKCS11KeyID = this.WindowsCodeSignPKCS11KeyID,
		WindowsCodeSignPKCS11PasswordFormat = this.WindowsCodeSignPKCS11PasswordFormat,
		WindowsCodeSignPKCS11Password = this.WindowsCodeSignPKCS11Password,
		WindowsCodeSignAzureVaultName = this.WindowsCodeSignAzureVaultName,
		WindowsCodeSignAzureCertName = this.WindowsCodeSignAzureCertName,
		WindowsCodeSignAzureAppID = this.WindowsCodeSignAzureAppID,
		WindowsCodeSignAzureAppSecretFormat = this.WindowsCodeSignAzureAppSecretFormat,
		WindowsCodeSignAzureAppSecret = this.WindowsCodeSignAzureAppSecret,
		WindowsCodeSignAzureTenantID = this.WindowsCodeSignAzureTenantID,
	};

	public void SetEmbeddedWindowsCodeSignProperties(WindowsCodeSignProperties other){
		this.WindowsCodeSignMethod = other.WindowsCodeSignMethod;
		this.WindowsCodeSignPKCS12FilePath = other.WindowsCodeSignPKCS12FilePath;
		this.WindowsCodeSignPKCS12PasswordFormat = other.WindowsCodeSignPKCS12PasswordFormat;
		this.WindowsCodeSignPKCS12Password = other.WindowsCodeSignPKCS12Password;
		this.WindowsCodeSignPKCS11Engine = other.WindowsCodeSignPKCS11Engine;
		this.WindowsCodeSignPKCS11Module = other.WindowsCodeSignPKCS11Module;
		this.WindowsCodeSignPKCS11Certfile = other.WindowsCodeSignPKCS11Certfile;
		this.WindowsCodeSignPKCS11KeyID = other.WindowsCodeSignPKCS11KeyID;
		this.WindowsCodeSignPKCS11PasswordFormat = other.WindowsCodeSignPKCS11PasswordFormat;
		this.WindowsCodeSignPKCS11Password = other.WindowsCodeSignPKCS11Password;
		this.WindowsCodeSignAzureVaultName = other.WindowsCodeSignAzureVaultName;
		this.WindowsCodeSignAzureCertName = other.WindowsCodeSignAzureCertName;
		this.WindowsCodeSignAzureAppID = other.WindowsCodeSignAzureAppID;
		this.WindowsCodeSignAzureAppSecretFormat = other.WindowsCodeSignAzureAppSecretFormat;
		this.WindowsCodeSignAzureAppSecret = other.WindowsCodeSignAzureAppSecret;
		this.WindowsCodeSignAzureTenantID = other.WindowsCodeSignAzureTenantID;
	}

}
}
