// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PublicBrandingProperties</c>
/// </summary>
public class PublicBrandingProperties {
	public string ProductName { get; set; } = "";
	public string CompanyName { get; set; } = "";
	public string HelpURL { get; set; } = "";
	public bool HelpIsPopup { get; set; }
	public string DefaultLoginServerURL { get; set; } = "";
	public string TileBackgroundColor { get; set; } = "";
	public string AccountRegisterURL { get; set; } = "";
	public bool HideBackgroundLogo { get; set; }

	public PublicBrandingProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PublicBrandingProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PublicBrandingProperties>(jsStr);
	}

}
}
