// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PVEBackupDisk</c>
/// </summary>
public class PVEBackupDisk {

	[JsonPropertyName("Device")]
	public string Device { get; set; } = string.Empty;

	[JsonPropertyName("DeviceNum")]
	public long DeviceNum { get; set; }

	public PVEBackupDisk(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PVEBackupDisk FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PVEBackupDisk>(jsStr);
	}

}
}
