// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PVEBackupNode</c>
/// </summary>
public class PVEBackupNode {

	[JsonPropertyName("IncludedVMs")]
	public List<PVEBackupVM> IncludedVMs { get; set; }

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("Selected")]
	public bool Selected { get; set; }

	public PVEBackupNode(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PVEBackupNode FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PVEBackupNode>(jsStr);
	}

}
}
