// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PVEDisk</c>
/// </summary>
public class PVEDisk {

	[JsonPropertyName("Device")]
	public string Device { get; set; } = string.Empty;

	[JsonPropertyName("DeviceNum")]
	public long DeviceNum { get; set; }

	[JsonPropertyName("StorageID")]
	public string StorageID { get; set; } = string.Empty;

	[JsonPropertyName("Volume")]
	public string Volume { get; set; } = string.Empty;

	[JsonPropertyName("Size")]
	public string Size { get; set; } = string.Empty;

	[JsonPropertyName("Format")]
	public string Format { get; set; } = string.Empty;

	[JsonPropertyName("Options")]
	public string Options { get; set; } = string.Empty;

	public PVEDisk(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PVEDisk FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PVEDisk>(jsStr);
	}

}
}
