// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PVEParams</c> This type is used in the EngineProps for an "engine1/proxmox" Protected Item. It represents
/// the entire Protected Item configuration. It is expected to be user-configurable.
/// Since Version : 25.8.0
/// </summary>
public class PVEParams {

	[JsonPropertyName("Everything")]
	public bool Everything { get; set; }

	[JsonPropertyName("Exclusions")]
	public List<PVEBackupNode> Exclusions { get; set; }

	[JsonPropertyName("Method")]
	//One of the PVE_BACKUP_METHOD constants
	public string Method { get; set; } = string.Empty;

	[JsonPropertyName("SSHConnection")]
	//Primary node URL + SSH credentials
	public SSHConnection SSHConnection { get; set; }

	[JsonPropertyName("Selections")]
	public List<PVEBackupNode> Selections { get; set; }

	[JsonPropertyName("UseCBT")]
	public bool UseCBT { get; set; }

	public PVEParams(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PVEParams FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PVEParams>(jsStr);
	}

}
}
