// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>PVEStorageName</c> PVEStorageName contains the name and type of storage configured on a Proxmox Cluster
/// </summary>
public class PVEStorageName {

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("Type")]
	public string Type { get; set; } = string.Empty;

	[JsonPropertyName("Content")]
	public List<string> Content { get; set; }

	public PVEStorageName(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public PVEStorageName FromJson(string jsStr) {
		return JsonSerializer.Deserialize<PVEStorageName>(jsStr);
	}

}
}
