// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>RatelimitOptions</c>
/// </summary>
public class RatelimitOptions {

	[JsonPropertyName("Rules")]
	public List<RatelimitRule> Rules { get; set; }

	public RatelimitOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public RatelimitOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<RatelimitOptions>(jsStr);
	}

}
}
