// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>RemoteStorageOption</c>
/// </summary>
public class RemoteStorageOption {

	[JsonPropertyName("Type")]
	public string Type { get; set; } = string.Empty;

	[JsonPropertyName("Description")]
	public string Description { get; set; } = string.Empty;

	[JsonPropertyName("RemoteAddress")]
	//For use with Comet Server (Storage Role / Auth Role)
	public string RemoteAddress { get; set; } = string.Empty;

	[JsonPropertyName("Username")]
	//For use with Comet Server (Storage Role / Auth Role)
	public string Username { get; set; } = string.Empty;

	[JsonPropertyName("Password")]
	//For use with Comet Server (Storage Role / Auth Role)
	public string Password { get; set; } = string.Empty;

	[JsonPropertyName("LDAP")]
	public ExternalLDAPAuthenticationSourceSettings LDAP { get; set; }

	[JsonPropertyName("OIDC")]
	public OidcConfig OIDC { get; set; }

	[JsonPropertyName("B2")]
	//Backblaze B2 (Storage Template / Constellation)
	public B2VirtualStorageRoleSettings B2 { get; set; }

	[JsonPropertyName("Wasabi")]
	//Wasabi, or Comet Storage powered by Wasabi (Storage Template / Constellation)
	public WasabiVirtualStorageRoleSettings Wasabi { get; set; }

	[JsonPropertyName("Custom")]
	//Custom Remote Bucket HTTP protocol (Storage Template)
	public CustomRemoteBucketSettings Custom { get; set; }

	[JsonPropertyName("S3")]
	//IDrive e2, or Custom IAM-compatible (Storage Template / Constellation)
	public S3GenericVirtualStorageRole S3 { get; set; }

	[JsonPropertyName("AWS")]
	//Amazon AWS (Storage Template / Constellation)
	public AmazonAWSVirtualStorageRoleSettings AWS { get; set; }

	[JsonPropertyName("Storj")]
	//Storj (Storage Template / Constellation)
	public StorjVirtualStorageRoleSetting Storj { get; set; }

	[JsonPropertyName("ImpPartner")]
	//Impossible Cloud Partner API (Storage Template / Constellation)
	public ImpossibleCloudPartnerTemplateSettings ImpPartner { get; set; }

	[JsonPropertyName("ImpUser")]
	//Impossible Cloud IAM API (Storage Template / Constellation)
	public ImpossibleCloudIAMTemplateSettings ImpUser { get; set; }

	[JsonPropertyName("StorageLimitEnabled")]
	public bool StorageLimitEnabled { get; set; }

	[JsonPropertyName("StorageLimitBytes")]
	public long StorageLimitBytes { get; set; }

	[JsonPropertyName("RebrandStorage")]
	public bool RebrandStorage { get; set; }

	[JsonPropertyName("ID")]
	public string ID { get; set; } = string.Empty;

	[JsonPropertyName("Default")]
	public bool Default { get; set; }

	public RemoteStorageOption(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public RemoteStorageOption FromJson(string jsStr) {
		return JsonSerializer.Deserialize<RemoteStorageOption>(jsStr);
	}

	public RemoteServerAddress GetEmbeddedRemoteServerAddress() => new RemoteServerAddress {
		Type = this.Type,
		Description = this.Description,
		RemoteAddress = this.RemoteAddress,
		Username = this.Username,
		Password = this.Password,
		LDAP = this.LDAP,
		OIDC = this.OIDC,
		B2 = this.B2,
		Wasabi = this.Wasabi,
		Custom = this.Custom,
		S3 = this.S3,
		AWS = this.AWS,
		Storj = this.Storj,
		ImpPartner = this.ImpPartner,
		ImpUser = this.ImpUser,
	};

	public void SetEmbeddedRemoteServerAddress(RemoteServerAddress other){
		this.Type = other.Type;
		this.Description = other.Description;
		this.RemoteAddress = other.RemoteAddress;
		this.Username = other.Username;
		this.Password = other.Password;
		this.LDAP = other.LDAP;
		this.OIDC = other.OIDC;
		this.B2 = other.B2;
		this.Wasabi = other.Wasabi;
		this.Custom = other.Custom;
		this.S3 = other.S3;
		this.AWS = other.AWS;
		this.Storj = other.Storj;
		this.ImpPartner = other.ImpPartner;
		this.ImpUser = other.ImpUser;
	}

}
}
