// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>RemoteServerAddress</c>
/// </summary>
public class RemoteServerAddress {
	public string Type { get; set; } = string.Empty;
	public string Description { get; set; } = string.Empty;
	public string RemoteAddress { get; set; } = string.Empty;
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public ExternalLDAPAuthenticationSourceSettings LDAP { get; set; }
	public B2VirtualStorageRoleSettings B2 { get; set; }
	public WasabiVirtualStorageRoleSettings Wasabi { get; set; }
	public CustomRemoteBucketSettings Custom { get; set; }
	public S3GenericVirtualStorageRole S3 { get; set; }
	//Amazon AWS - Virtual Storage Role
	public AmazonAWSVirtualStorageRoleSettings AWS { get; set; }
	public StorjVirtualStorageRoleSetting Storj { get; set; }

	public RemoteServerAddress(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public RemoteServerAddress FromJson(string jsStr) {
		return JsonSerializer.Deserialize<RemoteServerAddress>(jsStr);
	}

}
}
