// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>RequestStorageVaultResponseMessage</c>
/// </summary>
public class RequestStorageVaultResponseMessage {
	public long Status { get; set; }
	public string Message { get; set; } = string.Empty;
	public string DestinationID { get; set; } = string.Empty;

	public RequestStorageVaultResponseMessage(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public RequestStorageVaultResponseMessage FromJson(string jsStr) {
		return JsonSerializer.Deserialize<RequestStorageVaultResponseMessage>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
