// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>RestoreJobAdvancedOptions</c>
/// </summary>
public class RestoreJobAdvancedOptions {
	public long Type { get; set; }
	public bool OverwriteExistingFiles { get; set; }
	public bool OverwriteIfNewer { get; set; }
	public bool DestIsOriginalLocation { get; set; }
	public string DestPath { get; set; } = string.Empty;
	public List<string> ExactDestPaths { get; set; }
	public long ArchiveFormat { get; set; }
	public Office365Credential Office365Credential { get; set; }
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public string Host { get; set; } = string.Empty;
	public string Port { get; set; } = string.Empty;
	public bool UseSsl { get; set; }
	public bool SslAllowInvalid { get; set; }
	public string SslCaFile { get; set; } = string.Empty;
	public string SslCrtFile { get; set; } = string.Empty;
	public string SslKeyFile { get; set; } = string.Empty;
	public MSSQLLoginArgs MsSqlConnection { get; set; }

	public RestoreJobAdvancedOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public RestoreJobAdvancedOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<RestoreJobAdvancedOptions>(jsStr);
	}

}
}
