// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>S3DestinationLocation</c>
/// </summary>
public class S3DestinationLocation {
	public string S3Server { get; set; } = string.Empty;
	public bool S3UsesTLS { get; set; }
	public string S3AccessKey { get; set; } = string.Empty;
	public string S3SecretKey { get; set; } = string.Empty;
	public string S3BucketName { get; set; } = string.Empty;
	public string S3Subdir { get; set; } = string.Empty;
	public string S3CustomRegion { get; set; } = string.Empty;
	//If true, use legacy v2 signing. If false (default), use modern v4 signing
	public bool S3UsesV2Signing { get; set; }
	public bool S3RemoveDeleted { get; set; }
	public long S3ObjectLockDays { get; set; }

	public S3DestinationLocation(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public S3DestinationLocation FromJson(string jsStr) {
		return JsonSerializer.Deserialize<S3DestinationLocation>(jsStr);
	}

}
}
