// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SearchResultFileInfo</c>
/// </summary>
public class SearchResultFileInfo {

	[JsonPropertyName("path")]
	public string Path { get; set; } = string.Empty;

	[JsonPropertyName("name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("type")]
	public string Type { get; set; } = string.Empty;

	[JsonPropertyName("mode")]
	public string Mode { get; set; } = string.Empty;

	[JsonPropertyName("mtime")]
	public string Mtime { get; set; } = string.Empty;

	[JsonPropertyName("atime")]
	public string Atime { get; set; } = string.Empty;

	[JsonPropertyName("ctime")]
	public string Ctime { get; set; } = string.Empty;

	[JsonPropertyName("size")]
	public long Size { get; set; }

	public SearchResultFileInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SearchResultFileInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SearchResultFileInfo>(jsStr);
	}

}
}
