// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SelfBackupExportOptions</c>
/// </summary>
public class SelfBackupExportOptions {
	public DestinationLocation Location { get; set; }
	public string EncryptionKey { get; set; } = string.Empty;
	public ulong EncryptionKeyFormat { get; set; }
	public long Compression { get; set; }
	public bool ExcludeJobsDB { get; set; }
	public bool IncludeServerLogs { get; set; }
	public string RestrictToSingleOrgID { get; set; } = string.Empty;
	public long Index { get; set; }

	public SelfBackupExportOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SelfBackupExportOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SelfBackupExportOptions>(jsStr);
	}

}
}
