// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SelfBackupStatistics</c>
/// </summary>
public class SelfBackupStatistics {

	[JsonPropertyName("CurrentRunStart")]
	public long CurrentRunStart { get; set; }

	[JsonPropertyName("LastRunStart")]
	public long LastRunStart { get; set; }

	[JsonPropertyName("LastRunEnd")]
	public long LastRunEnd { get; set; }

	[JsonPropertyName("LastRunSuccess")]
	public bool LastRunSuccess { get; set; }

	[JsonPropertyName("LastRunSize")]
	public long LastRunSize { get; set; }

	public SelfBackupStatistics(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SelfBackupStatistics FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SelfBackupStatistics>(jsStr);
	}

}
}
