// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SelfBackupTarget</c>
/// </summary>
public class SelfBackupTarget {

	[JsonPropertyName("Schedule")]
	public List<ScheduleConfig> Schedule { get; set; }

	[JsonPropertyName("ScheduleTimezone")]
	//Timezone in IANA format
	public string ScheduleTimezone { get; set; } = string.Empty;

	[JsonPropertyName("RetentionPolicy")]
	public RetentionPolicy RetentionPolicy { get; set; }

	[JsonPropertyName("Location")]
	public DestinationLocation Location { get; set; }

	[JsonPropertyName("EncryptionKey")]
	public string EncryptionKey { get; set; } = string.Empty;

	[JsonPropertyName("EncryptionKeyFormat")]
	//One of the ENCRYPTIONMETHOD_ constants
	public ulong EncryptionKeyFormat { get; set; }

	[JsonPropertyName("Compression")]
	//One of the COMPRESS_LVL_ constants
	public long Compression { get; set; }

	[JsonPropertyName("ExcludeJobsDB")]
	//The jobs database is often the largest component of the System Self-Backup archive. By excluding it, you could run
	//the System Self-Backup more often.
	public bool ExcludeJobsDB { get; set; }

	[JsonPropertyName("IncludeServerLogs")]
	public bool IncludeServerLogs { get; set; }

	[JsonPropertyName("RestrictToSingleOrgID")]
	public string RestrictToSingleOrgID { get; set; } = string.Empty;

	[JsonPropertyName("Index")]
	public long Index { get; set; }

	public SelfBackupTarget(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SelfBackupTarget FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SelfBackupTarget>(jsStr);
	}

	public SelfBackupExportOptions GetEmbeddedSelfBackupExportOptions() => new SelfBackupExportOptions {
		Location = this.Location,
		EncryptionKey = this.EncryptionKey,
		EncryptionKeyFormat = this.EncryptionKeyFormat,
		Compression = this.Compression,
		ExcludeJobsDB = this.ExcludeJobsDB,
		IncludeServerLogs = this.IncludeServerLogs,
		RestrictToSingleOrgID = this.RestrictToSingleOrgID,
		Index = this.Index,
	};

	public void SetEmbeddedSelfBackupExportOptions(SelfBackupExportOptions other){
		this.Location = other.Location;
		this.EncryptionKey = other.EncryptionKey;
		this.EncryptionKeyFormat = other.EncryptionKeyFormat;
		this.Compression = other.Compression;
		this.ExcludeJobsDB = other.ExcludeJobsDB;
		this.IncludeServerLogs = other.IncludeServerLogs;
		this.RestrictToSingleOrgID = other.RestrictToSingleOrgID;
		this.Index = other.Index;
	}

}
}
