// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ServerMetaBrandingProperties</c>
/// </summary>
public class ServerMetaBrandingProperties {
	public string BrandName { get; set; } = string.Empty;
	public string ProductName { get; set; } = string.Empty;
	public bool HasImage { get; set; }
	public string ImageEtag { get; set; } = string.Empty;
	public string TopColor { get; set; } = string.Empty;
	public string AccentColor { get; set; } = string.Empty;
	public bool HideNewsArea { get; set; }
	public bool AllowUnauthenticatedDownloads { get; set; }
	public bool AllowAuthenticatedDownloads { get; set; }
	public long PruneLogsAfterDays { get; set; }
	public long ExpiredInSeconds { get; set; }

	public ServerMetaBrandingProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ServerMetaBrandingProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ServerMetaBrandingProperties>(jsStr);
	}

}
}
