// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>ServerConfigOptionsSoftwareBuildRoleFragment</c>
/// </summary>
public class ServerConfigOptionsSoftwareBuildRoleFragment {

	[JsonPropertyName("SoftwareBuildRole")]
	public SoftwareBuildRoleOptions SoftwareBuildRole { get; set; }

	public ServerConfigOptionsSoftwareBuildRoleFragment(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public ServerConfigOptionsSoftwareBuildRoleFragment FromJson(string jsStr) {
		return JsonSerializer.Deserialize<ServerConfigOptionsSoftwareBuildRoleFragment>(jsStr);
	}

}
}
