// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SessionOptions</c>
/// </summary>
public class SessionOptions {
	public ulong ExpiredInSeconds { get; set; }

	public SessionOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SessionOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SessionOptions>(jsStr);
	}

}
}
