// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SessionOptions</c>
/// </summary>
public class SessionOptions {

	[JsonPropertyName("ExpiredInSeconds")]
	//The number of seconds, after which an administrator should be automatically logged out of the Comet Server web
	//interface. If zero, will be replaced with DEFAULT_SESSIONTIMEOUT.
	public ulong ExpiredInSeconds { get; set; }

	public SessionOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SessionOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SessionOptions>(jsStr);
	}

}
}
