// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SoftwareUpdateNewsResponse</c>
/// </summary>
public class SoftwareUpdateNewsResponse {

	[JsonPropertyName("latest_stable")]
	public string LatestStable { get; set; } = "";

	[JsonPropertyName("latest_prerelease")]
	public string LatestPrerelease { get; set; } = "";

	[JsonPropertyName("downloads_url")]
	public string DownloadsURL { get; set; } = "";

	[JsonPropertyName("updates_info")]
	public List<string> WhatsNew { get; set; } = new List<string>();

	public SoftwareUpdateNewsResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SoftwareUpdateNewsResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SoftwareUpdateNewsResponse>(jsStr);
	}

}
}
