// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SoftwareBuildRoleOptions</c>
/// </summary>
public class SoftwareBuildRoleOptions {
	public bool RoleEnabled { get; set; }
	public bool AllowUnauthenticatedDownloads { get; set; }

	public SoftwareBuildRoleOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SoftwareBuildRoleOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SoftwareBuildRoleOptions>(jsStr);
	}

}
}
