// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SourceIncludePattern</c>
/// </summary>
public class SourceIncludePattern {
	public string TopDirectory { get; set; } = string.Empty;
	public string Value { get; set; } = string.Empty;

	public SourceIncludePattern(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SourceIncludePattern FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SourceIncludePattern>(jsStr);
	}

}
}
