// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SourceConfig</c>
/// </summary>
public class SourceConfig {

	[JsonPropertyName("Engine")]
	//One of the ENGINE_BUILTIN_ constants
	public string Engine { get; set; } = string.Empty;

	[JsonPropertyName("Description")]
	public string Description { get; set; } = string.Empty;

	[JsonPropertyName("OwnerDevice")]
	public string OwnerDevice { get; set; } = string.Empty;

	[JsonPropertyName("CreateTime")]
	//Unix timestamp in seconds
	public long CreateTime { get; set; }

	[JsonPropertyName("ModifyTime")]
	//Unix timestamp in seconds
	public long ModifyTime { get; set; }

	[JsonPropertyName("PreExec")]
	//Custom commands to run before the job
	public List<string> PreExec { get; set; }

	[JsonPropertyName("ThawExec")]
	//Custom commands to run after taking a disk snapshot
	public List<string> ThawExec { get; set; }

	[JsonPropertyName("PostExec")]
	//Custom commands to run after the job
	public List<string> PostExec { get; set; }

	[JsonPropertyName("EngineProps")]
	//Configuration for the selected Protected Item type. Each "Engine" supports
	//different configuration options for the EngineProps values.
	//
	//For engine1/file, Comet understands the following EngineProp keys:
	//
	//- Any key starting with INCLUDE: A path that is included
	//- Any key starting with EXCLUDE: An exclusion (glob format)
	//- Any key starting with REXCLUDE: An exclusion (regular expression format)
	//- Any key starting with PINCLUDE: A SourceIncludePattern type encoded in JSON format, describing an advanced
	//inclusion in glob format
	//- Any key starting with RINCLUDE: A SourceIncludePattern type encoded in JSON format, describing an advanced
	//inclusion in regular expression format
	//- Any key starting with SMBAUTH: A set of Windows network share credentials in WinSMBAuth JSON format
	//- USE_WIN_VSS: If present, the 'Take filesystem snapshot' checkbox is checked
	//- CONFIRM_EFS: If present, the 'Dismiss EFS warning' checkbox is checked
	//- RESCAN_UNCHANGED: If present, the 'Rescan unchanged files' checkbox is checked
	//- EXTRA_ATTRIBUTES: If present, the 'Back up extra system permissions and attributes' checkbox is checked
	//
	//For engine1/mssql, Comet understands the following EngineProp keys:
	//
	//- ALL_DATABASES: If present, include all databases with specified exclusions. If not present, only back up the
	//specified inclusions
	//- Any key starting with DATABASE- : A database that is included. Only valid if ALL_DATABASES is not present.
	//- Any key starting with EXCEPT-DATABASE- : A database that is excluded. Only valid if ALL_DATABASES is present.
	//- INSTANCE: The Microsoft SQL Server instance name
	//- USERNAME: The username to connect to Microsoft SQL Server
	//- PASSWORD: The password to connect to Microsoft SQL Server
	//- AUTHMODE: Either "windows" or "native" (corresponding to the declared MSSQL_AUTH_WINDOWS and MSSQL_AUTH_NATIVE
	//constant values). If not present, use native authentication if the USERNAME and/or PASSWORD fields are filled in, use
	//windows authentication if they are blank
	//- METHOD: Either "OLEDB_NATIVE" or "OLEDB_32" (corresponding to the declared MSSQL_METHOD_OLEDB_NATIVE and
	//MSSQL_METHOD_OLEDB_32 constant values). If not present, defaults to Native
	//- DIFFBASE: If present, take a "Full (base image)" backup job. Otherwise, take a "Full (copy only)" backup job.
	//- DIFFERENTIAL: If present, take a "Differential increment" backup job. Otherwise, take a "Full (copy only)" backup
	//job.
	//- LOGTRUNC: If present, take a "Log (truncating)" backup job. Otherwise, take a "Full (copy only)" backup job.
	//- LOGNOTRUNC: If present, take a "Log (no truncation)" backup job. Otherwise, take a "Full (copy only)" backup job.
	//
	//For engine1/stdout, Comet understands the following EngineProp keys:
	//
	//- COMMAND: The command to run
	//- WORKDIR: The working directory for the command
	//- SAVEAS: The virtual filename inside the backup snapshot
	//- Any key starting with EXTRACOMMAND- : Additional commands to run. Each value should be a JSON array of 3 strings,
	//equivalent to the COMMAND, WORKDIR, SAVEAS values.
	public Dictionary<string, string> EngineProps { get; set; }

	[JsonPropertyName("PolicySourceID")]
	//If set, this SourceConfig was added from a Policy with the specified ID.
	public string PolicySourceID { get; set; } = string.Empty;

	[JsonPropertyName("ExistingUserUpdate")]
	//For a Policy-defined SourceConfig, this field controls whether the Protected Item will stay linked with the policy.
	public bool ExistingUserUpdate { get; set; }

	[JsonPropertyName("OverrideDestinationRetention")]
	//By default, backup jobs from this Protected Item will be subject
	//to the overall retention policy for the Storage Vault. You can override the policy
	//for specific Storage Vaults by putting their destination ID as a key here.
	public Dictionary<string, RetentionPolicy> OverrideDestinationRetention { get; set; }

	[JsonPropertyName("Statistics")]
	public SourceStatistics Statistics { get; set; }

	public SourceConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SourceConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SourceConfig>(jsStr);
	}

}
}
