// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SourceConfig</c>
/// </summary>
public class SourceConfig {
	public string Engine { get; set; } = string.Empty;
	public string Description { get; set; } = string.Empty;
	public string OwnerDevice { get; set; } = string.Empty;
	public long CreateTime { get; set; }
	public long ModifyTime { get; set; }
	public List<string> PreExec { get; set; }
	public List<string> ThawExec { get; set; }
	public List<string> PostExec { get; set; }
	public Dictionary<string, string> EngineProps { get; set; }
	public Dictionary<string, RetentionPolicy> OverrideDestinationRetention { get; set; }
	public SourceStatistics Statistics { get; set; }

	public SourceConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SourceConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SourceConfig>(jsStr);
	}

}
}
