// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>SpannedStorageExtraInfo</c>
/// </summary>
public class SpannedStorageExtraInfo {
	public List<StorageFreeSpaceInfo> Targets { get; set; } = new List<StorageFreeSpaceInfo>();

	public SpannedStorageExtraInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public SpannedStorageExtraInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<SpannedStorageExtraInfo>(jsStr);
	}

}
}
