// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>StorageRoleOptions</c>
/// </summary>
public class StorageRoleOptions {

	[JsonPropertyName("RoleEnabled")]
	public bool RoleEnabled { get; set; }

	[JsonPropertyName("Storage")]
	public DestinationLocation Storage { get; set; }

	[Obsolete("Deprecated since Comet version 17.3.5")]

	[JsonPropertyName("LocalStorage")]
	public List<LocalStorageDirectory> LocalStorage_Legacy { get; set; }

	[JsonPropertyName("ReplicateTo")]
	public List<ReplicaServer> ReplicateTo { get; set; }

	public StorageRoleOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public StorageRoleOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<StorageRoleOptions>(jsStr);
	}

}
}
