// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>StorageFreeSpaceInfo</c>
/// </summary>
public class StorageFreeSpaceInfo {

	[JsonPropertyName("Unlimited")]
	public bool Unlimited { get; set; }

	[JsonPropertyName("UsedPercent")]
	public double UsedPercent { get; set; }

	[JsonPropertyName("AvailableBytes")]
	public ulong AvailableBytes { get; set; }

	[JsonPropertyName("Spanned")]
	public SpannedStorageExtraInfo Spanned { get; set; }

	[JsonPropertyName("B2")]
	public B2StorageExtraInfo B2 { get; set; }

	public StorageFreeSpaceInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public StorageFreeSpaceInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<StorageFreeSpaceInfo>(jsStr);
	}

}
}
