// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>StorjDestinationLocation</c>
/// </summary>
public class StorjDestinationLocation {
	public string SatelliteAddress { get; set; } = "";
	public string APIKey { get; set; } = "";
	public string Passphrase { get; set; } = "";
	public string StorjBucket { get; set; } = "";
	public string StorjBucketPrefix { get; set; } = "";

	public StorjDestinationLocation(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public StorjDestinationLocation FromJson(string jsStr) {
		return JsonSerializer.Deserialize<StorjDestinationLocation>(jsStr);
	}

}
}
