// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>StreamableEvent</c>
/// </summary>
public class StreamableEvent {

	[JsonPropertyName("Actor")]
	public string Actor { get; set; } = string.Empty;

	[JsonPropertyName("OwnerOrganizationID")]
	public string OwnerOrganizationID { get; set; } = string.Empty;

	[JsonPropertyName("ResourceID")]
	public string ResourceID { get; set; } = string.Empty;

	[JsonPropertyName("Type")]
	public long Type { get; set; }

	[JsonPropertyName("Timestamp")]
	public long Timestamp { get; set; }

	[JsonPropertyName("TypeString")]
	public string TypeString { get; set; } = string.Empty;

	[JsonPropertyName("Data")]
	public Object Data { get; set; }

	public StreamableEvent(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public StreamableEvent FromJson(string jsStr) {
		return JsonSerializer.Deserialize<StreamableEvent>(jsStr);
	}

}
}
