// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>TimeSpan</c>
/// </summary>
public class TimeSpan {
	public ulong FrequencyType { get; set; }
	public long Seconds { get; set; }

	public TimeSpan(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public TimeSpan FromJson(string jsStr) {
		return JsonSerializer.Deserialize<TimeSpan>(jsStr);
	}

}
}
