// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>TotpRegeneratedResponse</c>
/// </summary>
public class TotpRegeneratedResponse {
	//If the operation was successful, the status will be in the 200-299 range.
	public long Status { get; set; }
	public string Message { get; set; } = string.Empty;
	public string Image { get; set; } = string.Empty;
	public string URL { get; set; } = string.Empty;
	public string ProfileHash { get; set; } = string.Empty;

	public TotpRegeneratedResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public TotpRegeneratedResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<TotpRegeneratedResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
