// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>U2FRegisteredKey</c>
/// </summary>
[Obsolete("Deprecated since Comet version 21.12.0")]
public class U2FRegisteredKey {
	public string AppID { get; set; } = string.Empty;
	public string KeyHandle { get; set; } = string.Empty;
	public string Version { get; set; } = string.Empty;

	public U2FRegisteredKey(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public U2FRegisteredKey FromJson(string jsStr) {
		return JsonSerializer.Deserialize<U2FRegisteredKey>(jsStr);
	}

}
}
