// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>U2FRegistrationChallengeResponse</c>
/// </summary>
[Obsolete("Deprecated since Comet version 21.12.0")]
public class U2FRegistrationChallengeResponse {
	public long Status { get; set; }
	public string Message { get; set; } = "";
	public string ChallengeID { get; set; } = "";
	public string AppID { get; set; } = "";
	public List<U2FRegisteredKey> RegisteredKeys { get; set; } = new List<U2FRegisteredKey>();
	public List<U2FRegisterRequest> RegisterRequests { get; set; } = new List<U2FRegisterRequest>();

	public U2FRegistrationChallengeResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public U2FRegistrationChallengeResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<U2FRegistrationChallengeResponse>(jsStr);
	}

	public CometAPIResponseMessage GetEmbeddedCometAPIResponseMessage() => new CometAPIResponseMessage {
		Status = this.Status,
		Message = this.Message,
	};

	public void SetEmbeddedCometAPIResponseMessage(CometAPIResponseMessage other){
		this.Status = other.Status;
		this.Message = other.Message;
	}

}
}
