// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>U2FSignRequest</c>
/// </summary>
[Obsolete("Deprecated since Comet version 21.12.0")]
public class U2FSignRequest {

	[JsonPropertyName("ChallengeID")]
	public string ChallengeID { get; set; } = string.Empty;

	[JsonPropertyName("ChallengeData")]
	public string ChallengeData { get; set; } = string.Empty;

	[JsonPropertyName("AppID")]
	public string AppID { get; set; } = string.Empty;

	[JsonPropertyName("RegisteredKeys")]
	public List<U2FRegisteredKey> RegisteredKeys { get; set; }

	public U2FSignRequest(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public U2FSignRequest FromJson(string jsStr) {
		return JsonSerializer.Deserialize<U2FSignRequest>(jsStr);
	}

}
}
