// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>U2FSignResponse</c>
/// </summary>
[Obsolete("Deprecated since Comet version 21.12.0")]
public class U2FSignResponse {
	public string ChallengeID { get; set; } = string.Empty;
	public string KeyHandle { get; set; } = string.Empty;
	public string Signature { get; set; } = string.Empty;
	public string ClientData { get; set; } = string.Empty;

	public U2FSignResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public U2FSignResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<U2FSignResponse>(jsStr);
	}

}
}
