// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UninstallConfig</c> UninstallConfig allows configuring whether the target device will be uninstalled or
/// not.
/// </summary>
public class UninstallConfig {

	[JsonPropertyName("UninstallFlag")]
	//If this option is true, the target device will receive a message asking it to uninstall the Comet Backup app.
	public bool UninstallFlag { get; set; }

	[JsonPropertyName("RemoveConfigFile")]
	//This controls the "Remove all user settings from this device" option.
	public bool RemoveConfigFile { get; set; }

	public UninstallConfig(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UninstallConfig FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UninstallConfig>(jsStr);
	}

}
}
