// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UpdateCampaignDeviceStatus</c>
/// </summary>
public class UpdateCampaignDeviceStatus {
	public long Status { get; set; }

	public UpdateCampaignDeviceStatus(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UpdateCampaignDeviceStatus FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UpdateCampaignDeviceStatus>(jsStr);
	}

}
}
