// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UpdateCampaignOptions</c> This data structure describes which devices should receive a remote software
/// upgrade. Both the target version criteria (UpgradeOlder/ReinstallCurrentVer/DowngradeNewer) and the target device
/// criteria (ApplyDeviceFilter/DeviceFilter) must be met in order for the remote upgrade to be applied.
/// </summary>
public class UpdateCampaignOptions {
	public bool Active { get; set; }
	public bool UpgradeOlder { get; set; }
	public bool ReinstallCurrentVer { get; set; }
	public bool DowngradeNewer { get; set; }
	public bool ForceUpgradeRunning { get; set; }
	public bool ApplyDeviceFilter { get; set; }
	public SearchClause DeviceFilter { get; set; }

	public UpdateCampaignOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UpdateCampaignOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UpdateCampaignOptions>(jsStr);
	}

}
}
