// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UpdateCampaignProperties</c>
/// </summary>
public class UpdateCampaignProperties {
	public bool Active { get; set; }
	public bool UpgradeOlder { get; set; }
	public bool ReinstallCurrentVer { get; set; }
	public bool DowngradeNewer { get; set; }
	public bool ForceUpgradeRunning { get; set; }
	public bool ApplyDeviceFilter { get; set; }
	public SearchClause DeviceFilter { get; set; } = new SearchClause();
	public long StartTime { get; set; }
	public string TargetVersion { get; set; } = "";

	public UpdateCampaignProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UpdateCampaignProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UpdateCampaignProperties>(jsStr);
	}

	public UpdateCampaignOptions GetEmbeddedUpdateCampaignOptions() => new UpdateCampaignOptions {
		Active = this.Active,
		UpgradeOlder = this.UpgradeOlder,
		ReinstallCurrentVer = this.ReinstallCurrentVer,
		DowngradeNewer = this.DowngradeNewer,
		ForceUpgradeRunning = this.ForceUpgradeRunning,
		ApplyDeviceFilter = this.ApplyDeviceFilter,
		DeviceFilter = this.DeviceFilter,
	};

	public void SetEmbeddedUpdateCampaignOptions(UpdateCampaignOptions other){
		this.Active = other.Active;
		this.UpgradeOlder = other.UpgradeOlder;
		this.ReinstallCurrentVer = other.ReinstallCurrentVer;
		this.DowngradeNewer = other.DowngradeNewer;
		this.ForceUpgradeRunning = other.ForceUpgradeRunning;
		this.ApplyDeviceFilter = other.ApplyDeviceFilter;
		this.DeviceFilter = other.DeviceFilter;
	}

}
}
