// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UpdateCampaignStatus</c>
/// </summary>
public class UpdateCampaignStatus {
	public bool Active { get; set; }
	public bool UpgradeOlder { get; set; }
	public bool ReinstallCurrentVer { get; set; }
	public bool DowngradeNewer { get; set; }
	public bool ForceUpgradeRunning { get; set; }
	public bool ApplyDeviceFilter { get; set; }
	public SearchClause DeviceFilter { get; set; } = new SearchClause();
	public long StartTime { get; set; }
	public string TargetVersion { get; set; } = "";
	public List<UpdateCampaignStatusDeviceEntry> Devices { get; set; } = new List<UpdateCampaignStatusDeviceEntry>();

	public UpdateCampaignStatus(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UpdateCampaignStatus FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UpdateCampaignStatus>(jsStr);
	}

	public UpdateCampaignProperties GetEmbeddedUpdateCampaignProperties() => new UpdateCampaignProperties {
		Active = this.Active,
		UpgradeOlder = this.UpgradeOlder,
		ReinstallCurrentVer = this.ReinstallCurrentVer,
		DowngradeNewer = this.DowngradeNewer,
		ForceUpgradeRunning = this.ForceUpgradeRunning,
		ApplyDeviceFilter = this.ApplyDeviceFilter,
		DeviceFilter = this.DeviceFilter,
		StartTime = this.StartTime,
		TargetVersion = this.TargetVersion,
	};

	public void SetEmbeddedUpdateCampaignProperties(UpdateCampaignProperties other){
		this.Active = other.Active;
		this.UpgradeOlder = other.UpgradeOlder;
		this.ReinstallCurrentVer = other.ReinstallCurrentVer;
		this.DowngradeNewer = other.DowngradeNewer;
		this.ForceUpgradeRunning = other.ForceUpgradeRunning;
		this.ApplyDeviceFilter = other.ApplyDeviceFilter;
		this.DeviceFilter = other.DeviceFilter;
		this.StartTime = other.StartTime;
		this.TargetVersion = other.TargetVersion;
	}

}
}
