// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UserCustomEmailSettings</c>
/// </summary>
public class UserCustomEmailSettings {
	public List<EmailReportConfig> Reports { get; set; }

	public UserCustomEmailSettings(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UserCustomEmailSettings FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UserCustomEmailSettings>(jsStr);
	}

}
}
