// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>UserPolicy</c>
/// </summary>
public class UserPolicy {
	public bool PreventRequestStorageVault { get; set; }
	public bool PreventAddCustomStorageVault { get; set; }
	public bool PreventEditStorageVault { get; set; }
	public bool HideCloudStorageBranding { get; set; }
	public bool PreventDeleteStorageVault { get; set; }
	public StorageVaultProviderPolicy StorageVaultProviders { get; set; } = new StorageVaultProviderPolicy();
	public bool PreventNewProtectedItem { get; set; }
	public bool PreventEditProtectedItem { get; set; }
	public bool PreventDeleteProtectedItem { get; set; }
	public ProtectedItemEngineTypePolicy ProtectedItemEngineTypes { get; set; } = new ProtectedItemEngineTypePolicy();
	public List<ExtraFileExclusion> FileAndFolderMandatoryExclusions { get; set; } = new List<ExtraFileExclusion>();
	public long ModeScheduleSkipAlreadyRunning { get; set; }
	public long ModeAdminResetPassword { get; set; }
	public long ModeAdminViewFilenames { get; set; }
	public long ModeRequireUserResetPassword { get; set; }
	public bool PreventDeleteSingleSnapshots { get; set; }
	public bool PreventChangeAccountPassword { get; set; }
	public bool PreventChangeEmailSettings { get; set; }
	public bool PreventChangeAccountName { get; set; }
	public bool PreventOpenAppUI { get; set; }
	public bool RequirePasswordOpenAppUI { get; set; }
	public bool HideAppImport { get; set; }
	public bool HideAppVersion { get; set; }
	public bool PreventOpenWebUI { get; set; }
	public bool PreventViewDeviceNames { get; set; }
	public DefaultEmailReportPolicy DefaultEmailReports { get; set; } = new DefaultEmailReportPolicy();
	public RetentionPolicy DefaultStorageVaultRetention { get; set; } = new RetentionPolicy();
	public bool EnforceStorageVaultRetention { get; set; }
	public bool PreventProtectedItemRetention { get; set; }
	public Dictionary<string, SourceConfig> DefaultSources { get; set; } = new Dictionary<string, SourceConfig>();
	public Dictionary<string, BackupRuleConfig> DefaultSourcesBackupRules { get; set; } = new Dictionary<string, BackupRuleConfig>();
	public Dictionary<string, DefaultSourceWithOSRestriction> DefaultSourcesWithOSRestriction { get; set; } = new Dictionary<string, DefaultSourceWithOSRestriction>();
	public Dictionary<string, BackupRuleConfig> DefaultBackupRules { get; set; } = new Dictionary<string, BackupRuleConfig>();
	public ulong RandomDelaySecs { get; set; }

	public UserPolicy(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public UserPolicy FromJson(string jsStr) {
		return JsonSerializer.Deserialize<UserPolicy>(jsStr);
	}

}
}
