// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMDiskInfo</c>
/// Since Version : 24.12.x
/// </summary>
public class VMDiskInfo {

	[JsonPropertyName("Path")]
	//Relative path within this backup job snapshot to root disk files
	public string Path { get; set; } = string.Empty;

	[JsonPropertyName("Size")]
	//The virtual size of the virtual disk
	public long Size { get; set; }

	[JsonPropertyName("Controller")]
	//Controller number where the disk is associated to
	public long Controller { get; set; }

	[JsonPropertyName("DeviceNum")]
	//Device number within the controller
	public long DeviceNum { get; set; }

	public VMDiskInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMDiskInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMDiskInfo>(jsStr);
	}

}
}
