// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMDKSnapshotViewOptions</c>
/// </summary>
public class VMDKSnapshotViewOptions {
	public bool Enabled { get; set; }
	public string PartitionGUID { get; set; } = string.Empty;
	public string ListPath { get; set; } = string.Empty;
	public string PartitionName { get; set; } = string.Empty;

	public VMDKSnapshotViewOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMDKSnapshotViewOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMDKSnapshotViewOptions>(jsStr);
	}

}
}
