// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMInfo</c>
/// Since Version : 24.12.x
/// </summary>
public class VMInfo {

	[JsonPropertyName("ID")]
	public string ID { get; set; } = string.Empty;

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("CPUCores")]
	public long CPUCores { get; set; }

	[JsonPropertyName("RamBytes")]
	//Bytes
	public long RamBytes { get; set; }

	[JsonPropertyName("FirmwareType")]
	//The BIOS mode of this machine e.g. "Legacy"|"UEFI"
	public string FirmwareType { get; set; } = string.Empty;

	[JsonPropertyName("ConfigPath")]
	//Relative path to config file or directory, if supported by this Protected Item type
	public string ConfigPath { get; set; } = string.Empty;

	[JsonPropertyName("Disks")]
	public List<VMDiskInfo> Disks { get; set; }

	public VMInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMInfo>(jsStr);
	}

}
}
