// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMInfoList</c>
/// Since Version : 24.12.x
/// </summary>
public class VMInfoList {

	[JsonPropertyName("VMs")]
	public List<VMInfo> VMs { get; set; }

	public VMInfoList(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMInfoList FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMInfoList>(jsStr);
	}

}
}
