// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMwareConnection</c>
/// </summary>
public class VMwareConnection {

	[JsonPropertyName("ConnectionType")]
	//One of the VMWARE_CONNECTION_ constants
	public string ConnectionType { get; set; } = string.Empty;

	[Obsolete("Deprecated since Comet version 23.9.11")]

	[JsonPropertyName("SSH")]
	public SSHConnection SSH { get; set; }

	[JsonPropertyName("VSphere")]
	public VSphereConnection VSphere { get; set; }

	public VMwareConnection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMwareConnection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMwareConnection>(jsStr);
	}

}
}
