// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMwareNetworkInfo</c> VMwareNetworkInfo describes a single VMware network within a VMware datacenter.
/// </summary>
public class VMwareNetworkInfo {

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	public VMwareNetworkInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMwareNetworkInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMwareNetworkInfo>(jsStr);
	}

}
}
