// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMwareRestoreTargetOptions</c> VMwareRestoreTargetOptions is used when restoring a virtual machine backup
/// job into VMware, using the RESTORETYPE_VMHOST option.
/// Since Version : 24.12.x
/// </summary>
public class VMwareRestoreTargetOptions {

	[JsonPropertyName("Datacenter")]
	//The name of the VMware Datacenter to restore into. If blank and there is only one Datacenter in the vSphere
	//connection, it is chosen.
	public string Datacenter { get; set; } = string.Empty;

	[JsonPropertyName("Host")]
	//The name of the VMware Host within the VMware Datacenter to restore into. If blank and there is only one Datacenter
	//in the vSphere connection, it is chosen.
	public string Host { get; set; } = string.Empty;

	[JsonPropertyName("DatastorePath")]
	//The name of the VMware Datastore on the VMware Host to restore into. If blank and there is only one Datacenter in the
	//vSphere connection, it is chosen.
	public string DatastorePath { get; set; } = string.Empty;

	[JsonPropertyName("Network")]
	//The name of the VMware Network on the VMware Host to restore into. If blank and there is only one network on the
	//target vSphere connection, it is chosen.
	public string Network { get; set; } = string.Empty;

	[JsonPropertyName("Connection")]
	public VMwareConnection Connection { get; set; }

	public VMwareRestoreTargetOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMwareRestoreTargetOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMwareRestoreTargetOptions>(jsStr);
	}

}
}
