// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VMwareDatastoreInfo</c> VMwareDatastoreInfo describes a single VMware datastore within a VMware datacenter.
/// </summary>
public class VMwareDatastoreInfo {

	[JsonPropertyName("Name")]
	public string Name { get; set; } = string.Empty;

	public VMwareDatastoreInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VMwareDatastoreInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VMwareDatastoreInfo>(jsStr);
	}

}
}
