// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VSphereConnection</c>
/// </summary>
public class VSphereConnection {

	[JsonPropertyName("Hostname")]
	public string Hostname { get; set; } = string.Empty;

	[JsonPropertyName("Https")]
	public bool Https { get; set; }

	[JsonPropertyName("AllowInvalidCertificate")]
	public bool AllowInvalidCertificate { get; set; }

	[JsonPropertyName("Username")]
	public string Username { get; set; } = string.Empty;

	[JsonPropertyName("Password")]
	public string Password { get; set; } = string.Empty;

	[JsonPropertyName("ThumbPrint")]
	public string ThumbPrint { get; set; } = string.Empty;

	public VSphereConnection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VSphereConnection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VSphereConnection>(jsStr);
	}

}
}
