// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>VSSWriterInfo</c>
/// </summary>
public class VSSWriterInfo {

	[JsonPropertyName("DisplayName")]
	public string DisplayName { get; set; } = string.Empty;

	[JsonPropertyName("Components")]
	public List<VSSComponent> Components { get; set; }

	public VSSWriterInfo(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public VSSWriterInfo FromJson(string jsStr) {
		return JsonSerializer.Deserialize<VSSWriterInfo>(jsStr);
	}

}
}
