// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnCredential</c>
/// </summary>
public class WebAuthnCredential {
	public byte[] PublicKey { get; set; }
	public string AttestationType { get; set; } = string.Empty;
	public byte[] AAGUID { get; set; }
	public uint SignCount { get; set; }
	public bool CloneWarning { get; set; }

	public WebAuthnCredential(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnCredential FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnCredential>(jsStr);
	}

}
}
