// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnAuthenticatorSelection</c>
/// </summary>
public class WebAuthnAuthenticatorSelection {

	[JsonPropertyName("authenticatorAttachment")]
	public string AuthenticatorAttachment { get; set; } = string.Empty;

	[JsonPropertyName("requireResidentKey")]
	public bool RequireResidentKey { get; set; }

	[JsonPropertyName("residentKey")]
	public string ResidentKey { get; set; } = string.Empty;

	[JsonPropertyName("userVerification")]
	public string UserVerification { get; set; } = string.Empty;

	public WebAuthnAuthenticatorSelection(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnAuthenticatorSelection FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnAuthenticatorSelection>(jsStr);
	}

}
}
