// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnRelyingPartyEntity</c>
/// </summary>
public class WebAuthnRelyingPartyEntity {

	[JsonPropertyName("name")]
	public string Name { get; set; } = string.Empty;

	[JsonPropertyName("icon")]
	public string Icon { get; set; } = string.Empty;

	[JsonPropertyName("id")]
	public string ID { get; set; } = string.Empty;

	public WebAuthnRelyingPartyEntity(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnRelyingPartyEntity FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnRelyingPartyEntity>(jsStr);
	}

	public WebAuthnCredentialEntity GetEmbeddedWebAuthnCredentialEntity() => new WebAuthnCredentialEntity {
		Name = this.Name,
		Icon = this.Icon,
	};

	public void SetEmbeddedWebAuthnCredentialEntity(WebAuthnCredentialEntity other){
		this.Name = other.Name;
		this.Icon = other.Icon;
	}

}
}
