// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnSignResponse</c>
/// </summary>
public class WebAuthnSignResponse {
	public string ChallengeID { get; set; } = string.Empty;
	public string CredentialJSON { get; set; } = string.Empty;

	public WebAuthnSignResponse(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnSignResponse FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnSignResponse>(jsStr);
	}

}
}
