// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnUserEntity</c>
/// </summary>
public class WebAuthnUserEntity {

	[JsonPropertyName("name")]
	public string Name { get; set; } = "";

	[JsonPropertyName("icon")]
	public string Icon { get; set; } = "";

	[JsonPropertyName("displayName")]
	public string DisplayName { get; set; } = "";

	[JsonPropertyName("id")]
	public byte[] ID { get; set; }

	public WebAuthnUserEntity(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnUserEntity FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnUserEntity>(jsStr);
	}

	public WebAuthnCredentialEntity GetEmbeddedWebAuthnCredentialEntity() => new WebAuthnCredentialEntity {
		Name = this.Name,
		Icon = this.Icon,
	};

	public void SetEmbeddedWebAuthnCredentialEntity(WebAuthnCredentialEntity other){
		this.Name = other.Name;
		this.Icon = other.Icon;
	}

}
}
