// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnSignRequest</c>
/// </summary>
public class WebAuthnSignRequest {

	[JsonPropertyName("ChallengeID")]
	public string ChallengeID { get; set; } = string.Empty;

	[JsonPropertyName("Assertion")]
	public WebAuthnCredentialAssertion Assertion { get; set; }

	public WebAuthnSignRequest(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnSignRequest FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnSignRequest>(jsStr);
	}

}
}
