// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnPublicKeyCredentialCreationOptions</c>
/// </summary>
public class WebAuthnPublicKeyCredentialCreationOptions {

	[JsonPropertyName("challenge")]
	public byte[] Challenge { get; set; }

	[JsonPropertyName("rp")]
	public WebAuthnRelyingPartyEntity RelyingParty { get; set; }

	[JsonPropertyName("user")]
	public WebAuthnUserEntity User { get; set; }

	[JsonPropertyName("pubKeyCredParams")]
	public List<WebAuthnCredentialParameter> Parameters { get; set; }

	[JsonPropertyName("authenticatorSelection")]
	public WebAuthnAuthenticatorSelection AuthenticatorSelection { get; set; }

	[JsonPropertyName("timeout")]
	public long Timeout { get; set; }

	[JsonPropertyName("excludeCredentials")]
	public List<WebAuthnCredentialDescriptor> CredentialExcludeList { get; set; }

	[JsonPropertyName("extensions")]
	public Dictionary<string, Object> Extensions { get; set; }

	[JsonPropertyName("attestation")]
	public string Attestation { get; set; } = string.Empty;

	public WebAuthnPublicKeyCredentialCreationOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnPublicKeyCredentialCreationOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnPublicKeyCredentialCreationOptions>(jsStr);
	}

}
}
