// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnCredentialAssertion</c>
/// </summary>
public class WebAuthnCredentialAssertion {

	[JsonPropertyName("publicKey")]
	public WebAuthnPublicKeyCredentialRequestOptions Response { get; set; } = new WebAuthnPublicKeyCredentialRequestOptions();

	public WebAuthnCredentialAssertion(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnCredentialAssertion FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnCredentialAssertion>(jsStr);
	}

}
}
