// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnCredentialDescriptor</c>
/// </summary>
public class WebAuthnCredentialDescriptor {

	[JsonPropertyName("type")]
	public string Type { get; set; } = "";

	[JsonPropertyName("id")]
	public byte[] CredentialID { get; set; }

	[JsonPropertyName("transports")]
	public List<string> Transport { get; set; } = new List<string>();

	public WebAuthnCredentialDescriptor(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnCredentialDescriptor FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnCredentialDescriptor>(jsStr);
	}

}
}
