// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnPublicKeyCredentialRequestOptions</c>
/// </summary>
public class WebAuthnPublicKeyCredentialRequestOptions {

	[JsonPropertyName("challenge")]
	public byte[] Challenge { get; set; }

	[JsonPropertyName("timeout")]
	public long Timeout { get; set; }

	[JsonPropertyName("rpId")]
	public string RelyingPartyID { get; set; } = "";

	[JsonPropertyName("allowCredentials")]
	public List<WebAuthnCredentialDescriptor> AllowedCredentials { get; set; } = new List<WebAuthnCredentialDescriptor>();

	[JsonPropertyName("userVerification")]
	public string UserVerification { get; set; } = "";

	[JsonPropertyName("extensions")]
	public Dictionary<string, Object> Extensions { get; set; } = new Dictionary<string, Object>();

	public WebAuthnPublicKeyCredentialRequestOptions(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnPublicKeyCredentialRequestOptions FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnPublicKeyCredentialRequestOptions>(jsStr);
	}

}
}
