// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebAuthnCredentialEntity</c>
/// </summary>
public class WebAuthnCredentialEntity {

	[JsonPropertyName("name")]
	public string Name { get; set; } = "";

	[JsonPropertyName("icon")]
	public string Icon { get; set; } = "";

	public WebAuthnCredentialEntity(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebAuthnCredentialEntity FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebAuthnCredentialEntity>(jsStr);
	}

}
}
