// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebDavDestinationLocation</c>
/// Since Version : 23.6.9
/// </summary>
public class WebDavDestinationLocation {

	[JsonPropertyName("DavServer")]
	//The URL of the WebDAV server, including http/https and any custom port
	public string DavServer { get; set; } = string.Empty;

	[JsonPropertyName("UserName")]
	//The username for logging in to the WebDAV server
	public string UserName { get; set; } = string.Empty;

	[JsonPropertyName("AccessKey")]
	//The password for logging in to the WebDAV server
	public string AccessKey { get; set; } = string.Empty;

	[JsonPropertyName("Path")]
	//The target directory path within the WebDAV server
	public string Path { get; set; } = string.Empty;

	public WebDavDestinationLocation(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebDavDestinationLocation FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebDavDestinationLocation>(jsStr);
	}

}
}
