// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WebInterfaceBrandingProperties</c>
/// </summary>
public class WebInterfaceBrandingProperties {
	public long BrandingStyleType { get; set; }
	public string BrandName { get; set; } = string.Empty;
	public string LogoImage { get; set; } = string.Empty;
	public string TopColor { get; set; } = string.Empty;
	public string AccentColor { get; set; } = string.Empty;
	public string Favicon { get; set; } = string.Empty;
	public bool HideNewsArea { get; set; }

	public WebInterfaceBrandingProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WebInterfaceBrandingProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WebInterfaceBrandingProperties>(jsStr);
	}

}
}
