// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WindowsCodeSignProperties</c>
/// </summary>
public class WindowsCodeSignProperties {
	public long WindowsCodeSignMethod { get; set; }
	public string WindowsCodeSignPKCS12FilePath { get; set; } = "";
	public ulong WindowsCodeSignPKCS12PasswordFormat { get; set; }
	public string WindowsCodeSignPKCS12Password { get; set; } = "";
	public string WindowsCodeSignPKCS11Engine { get; set; } = "";
	public string WindowsCodeSignPKCS11Module { get; set; } = "";

	[Obsolete("Deprecated since Comet version 22.12.7")]
	public string WindowsCodeSignPKCS11Certfile { get; set; } = "";
	public string WindowsCodeSignPKCS11KeyID { get; set; } = "";
	public ulong WindowsCodeSignPKCS11PasswordFormat { get; set; }
	public string WindowsCodeSignPKCS11Password { get; set; } = "";
	public string WindowsCodeSignAzureVaultName { get; set; } = "";
	public string WindowsCodeSignAzureCertName { get; set; } = "";
	public string WindowsCodeSignAzureAppID { get; set; } = "";
	public ulong WindowsCodeSignAzureAppSecretFormat { get; set; }
	public string WindowsCodeSignAzureAppSecret { get; set; } = "";
	public string WindowsCodeSignAzureTenantID { get; set; } = "";

	public WindowsCodeSignProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WindowsCodeSignProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WindowsCodeSignProperties>(jsStr);
	}

}
}
