// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WindowsCodeSignProperties</c>
/// </summary>
public class WindowsCodeSignProperties {

	[JsonPropertyName("WindowsCodeSignMethod")]
	//One of the WINDOWSCODESIGN_METHOD_ constants
	public long WindowsCodeSignMethod { get; set; }

	[JsonPropertyName("WindowsCodeSignPKCS12FilePath")]
	public string WindowsCodeSignPKCS12FilePath { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS12PasswordFormat")]
	//One of the ENCRYPTIONMETHOD_ constants
	public ulong WindowsCodeSignPKCS12PasswordFormat { get; set; }

	[JsonPropertyName("WindowsCodeSignPKCS12Password")]
	public string WindowsCodeSignPKCS12Password { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS11Engine")]
	public string WindowsCodeSignPKCS11Engine { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS11Module")]
	public string WindowsCodeSignPKCS11Module { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS11Certfile")]
	//This field was deprecated between 23.3.0 and 23.6.x, but is now used again.
	public string WindowsCodeSignPKCS11Certfile { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS11KeyID")]
	public string WindowsCodeSignPKCS11KeyID { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignPKCS11PasswordFormat")]
	//One of the ENCRYPTIONMETHOD_ constants
	public ulong WindowsCodeSignPKCS11PasswordFormat { get; set; }

	[JsonPropertyName("WindowsCodeSignPKCS11Password")]
	public string WindowsCodeSignPKCS11Password { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignAzureVaultName")]
	public string WindowsCodeSignAzureVaultName { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignAzureCertName")]
	public string WindowsCodeSignAzureCertName { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignAzureAppID")]
	public string WindowsCodeSignAzureAppID { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignAzureAppSecretFormat")]
	//One of the ENCRYPTIONMETHOD_ constants
	public ulong WindowsCodeSignAzureAppSecretFormat { get; set; }

	[JsonPropertyName("WindowsCodeSignAzureAppSecret")]
	public string WindowsCodeSignAzureAppSecret { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignAzureTenantID")]
	public string WindowsCodeSignAzureTenantID { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignRelicServerURL")]
	//URL of the SAS Relic server, with protocol (https://) and trailing slash
	public string WindowsCodeSignRelicServerURL { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignRelicKeypairFile")]
	//The SAS Relic client keypair in PEM format
	public string WindowsCodeSignRelicKeypairFile { get; set; } = string.Empty;

	[JsonPropertyName("WindowsCodeSignRelicKeyName")]
	//The name of the key to select on the remote SAS Relic server
	public string WindowsCodeSignRelicKeyName { get; set; } = string.Empty;

	public WindowsCodeSignProperties(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WindowsCodeSignProperties FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WindowsCodeSignProperties>(jsStr);
	}

}
}
