// AUTOGENERATED, DO NOT EDIT

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CometBackup.CometAPI.SDK {
/// <summary>
/// Class <c>WinSMBAuth</c>
/// </summary>
public class WinSMBAuth {
	public string SharePath { get; set; } = string.Empty;
	public string Username { get; set; } = string.Empty;
	public string Password { get; set; } = string.Empty;
	public ulong PasswordFormat { get; set; }

	public WinSMBAuth(){ }

	public string ToJson() {
		return JsonSerializer.Serialize(this);
	}

	static public WinSMBAuth FromJson(string jsStr) {
		return JsonSerializer.Deserialize<WinSMBAuth>(jsStr);
	}

}
}
